### ISSUE TITLE
调用llm._call_async方法报错

### ISSUE THREAD

**Issue by godlovefei** [tencentmusic/supersonic#1001]
NotImplementedError: Async generation not implemented for this LLM.

**Comment by jerryjzhang** [comment]
用的是哪个LLM？看起来不支持异步生成

**Comment by godlovefei** [comment]
@jerryjzhang Lamma3，本地化部署，我看Lanhchain是支持异步的，难道是Lamma3不支持么？另外我尝试了chatGLM3也是同样问题。langchain的issues也貌似查到了同样的问题 https://github.com/langchain-ai/langchain/issues/6932

**Comment by jerryjzhang** [comment]
> @jerryjzhang Lamma3，本地化部署，我看Lanhchain是支持异步的，难道是Lamma3不支持么？另外我尝试了chatGLM3也是同样问题。langchain的issues也貌似查到了同样的问题 [langchain-ai/langchain#6932](https://github.com/langchain-ai/langchain/issues/6932)

我们也来验证下试试看

**Comment by godlovefei** [comment]
@jerryjzhang 有进展可以分享下，不胜感激
