### ISSUE TITLE
是否支持 "按天展示最近10天内每一天访问次数最多的部门" 问题？

### ISSUE THREAD

**Issue by jersy** [tencentmusic/supersonic#1013]
基本最新的master分支代码，提了"按天展示最近10天内每一天访问次数最多的部门"问题，无法的到正确答案。

@jerryjzhang 我有个疑问，如果是这样的问题，是不是意味着我要自己去构建一个新的模型才能回答这个问题？

另外在多问一个问题，目前的语义解析 有哪些局限？ 

```
"llmResp": {
    "query": "按天展示最近10天内每一天访问次数最多的部门",
    "modelName": "超音数",
    "sqlRespMap": {
        "SELECT 数据日期, 部门, MAX(访问次数) FROM 超音数 WHERE datediff('day', 数据日期, '2024-05-17') <= 10 GROUP BY 数据日期, 部门 ORDER BY MAX(访问次数) DESC": {
            "sqlWeight": 1.0,
            "fewShots": [
                {
                    "questionAugmented": "内容库 按部门统计访问次数 top10 的部门 (补充信息:。当前的日期是2023-09-10) (备注: )",
                    "dbSchema": "Table: 内容库产品, Columns = [\"用户名\", \"部门\", \"模块\", \"访问时长\", \"访问次数\", \"访问人数\", \"数据日期\"]\nForeign_keys: []",
                    "generatedSchemaLinkings": "[访问次数,部门,10]",
                    "question": "内容库 按部门统计访问次数 top10 的部门",
                    "generatedSchemaLinkingCoT": "Let’s think step by step. In the question \"内容库 按部门统计访问次数 top10 的部门 (补充信息:。当前的日期是2023-09-10) (备注: )\", we are asked:\n\"计访问次数 \" so we need column = [访问次数]\n\" 的部门 (\" so we need column = [部门]\nBased on the tables, columns, and Foreign_keys, The set of possible cell values are = [10]. So the Schema_links are:\nSchema_links: [访问次数,部门,10]",
                    "sql": "SELECT 部门, SUM(访问次数) FROM 内容库产品 GROUP BY 部门 ORDER BY SUM(访问次数) DESC LIMIT 10"
                },
                {
                    "questionAugmented": "近3天海田飞系MPPM结算播放份额 (补充信息:’'海田飞系'‘是一个’严选版权归属系‘。当前的日期是2023-08-21) (备注: )",
                    "dbSchema": "Table: 严选, Columns = [\"严选版权归属系\", \"付费模式\", \"结算播放份额\", \"付费用户结算播放份额\", \"数据日期\"]\nForeign_keys: []",
                    "generatedSchemaLinkings": "[结算播放份额,严选版权归属系,数据日期,海田飞系,3,day]",
                    "question": "近3天海田飞系MPPM结算播放份额",
                    "generatedSchemaLinkingCoT": "Let’s think step by step. In the question \"近3天海田飞系MPPM结算播放份额 (补充信息:’'海田飞系'‘是一个’严选版权归属系‘。当前的日期是2023-08-21) (备注: )\", we are asked:\n\"结算播放份额 \" so we need column = [结算播放份额]\n\"严选版权归属系\" so we need column = [严选版权归属系]\n\"当前的日期是\" so we need column = [数据日期]\nBased on the tables, columns, and Foreign_keys, The set of possible cell values are = [海田飞系,3,day]. So the Schema_links are:\nSchema_links: [结算播放份额,严选版权归属系,数据日期,海田飞系,3,day]",
                    "sql": "SELECT 严选版权归属系, 结算播放份额 FROM 严选 WHERE 严选版权归属系 = '海田飞系' AND datediff('day', 数据日期, '2023-08-21') <= 3 "
                },
                {
                    "questionAugmented": "2023年以来发行的歌曲中，有哪些在近7天播放超过一千万的 (补充信息:’'514129144'‘是一个’MPPM歌曲ID‘。当前的日期是2023-08-12) (备注: )",
                    "dbSchema": "Table: 歌曲库, Columns = [\"发行日期\", \"歌曲语言\", \"歌曲来源\", \"歌曲流派\", \"歌曲名\", \"歌曲版本\", \"歌曲类型\", \"发行时间\", \"数据日期\"]\nForeign_keys: []",
                    "generatedSchemaLinkings": "[歌曲名,结算播放量,发行日期,数据日期,10000000,2023-01-01,7,day]",
                    "question": "2023年以来发行的歌曲中，有哪些在近7天播放超过一千万的",
                    "generatedSchemaLinkingCoT": "Let’s think step by step. In the question \"2023年以来发行的歌曲中，有哪些在近7天播放超过一千万的 (补充信息:’'514129144'‘是一个’MPPM歌曲ID‘。当前的日期是2023-08-12) (备注: )\", we are asked:\n\"的歌曲中，有\" so we need column = [歌曲名]\n\"天播放超过一\" so we need column = [结算播放量]\n\"年以来发行的\" so we need column = [发行日期]\n\"当前的日期是\" so we need column = [数据日期]\nBased on the tables, columns, and Foreign_keys, The set of possible cell values are = [10000000,2023-01-01,7,day]. So the Schema_links are:\nSchema_links: [歌曲名,结算播放量,发行日期,数据日期,10000000,2023-01-01,7,day]",
                    "sql": "SELECT 歌曲名 FROM 歌曲库 WHERE 发行日期 >= '2023-01-01' AND datediff('day', 数据日期, '2023-08-12') <= 7 AND 结算播放量 > 10000000"
                }
                --截取部分
            ]
        }
    }
},
"sqlInfo": {
                    "s2SQL": "SELECT 数据日期, 部门, MAX(访问次数) FROM 超音数 WHERE datediff('day', 数据日期, '2024-05-17') <= 10 GROUP BY 数据日期, 部门"
                }
```
                
![企业微信截图_1fe64ef1-95b8-412b-b2b7-937ecbe71fe0](https://github.com/tencentmusic/supersonic/assets/1180793/b9a8ed14-3741-4a54-bbf8-5859a01e46ba)

**Comment by jersy** [comment]
@mainmainer @jerryjzhang   是不是提的这个问题比较业余？但是也不是每个用户都会用吧

**Comment by jersy** [comment]
@jerryjzhang 大佬看看这个问题啊

**Comment by mainmainer** [comment]
> SELECT 数据日期, 部门, MAX(访问次数) FROM 超音数 WHERE datediff('day', 数据日期, '2024-05-17') <= 10 GROUP BY 数据日期, 部门

生成的s2sql是“SELECT 数据日期, 部门, MAX(访问次数) FROM 超音数 WHERE datediff('day', 数据日期, '2024-05-17') <= 10 GROUP BY 数据日期, 部门”，感觉这个sql是对的。你觉得是查询结果有问题还是sql生成有问题

**Comment by jersy** [comment]
@mainmainer 最终执行的sql不对，应该取当天所有部门里访问量最大的部门， 最终sql按 sys_imp_date,department进行分组，变成了每个部门当天最大访问次数了。 
我用的默认数据集进行测试的，你可以在你本地进行一下测试


![企业微信截图_69f47127-8b17-43a9-9afb-aeae5cf9d775](https://github.com/tencentmusic/supersonic/assets/1180793/f8064b16-c88c-49a5-8220-e606a16e63b0)


![企业微信截图_1fe64ef1-95b8-412b-b2b7-937ecbe71fe0](https://github.com/tencentmusic/supersonic/assets/1180793/1fa13493-5345-4d30-ba6e-b8908f67d247)

**Comment by jerryjzhang** [comment]
> @mainmainer 最终执行的sql不对，应该取当天所有部门里访问量最大的部门， 最终sql按 sys_imp_date,department进行分组，变成了每个部门当天最大访问次数了。 我用的默认数据集进行测试的，你可以在你本地进行一下测试
> 
> ![企业微信截图_69f47127-8b17-43a9-9afb-aeae5cf9d775](https://private-user-images.githubusercontent.com/1180793/332645282-f8064b16-c88c-49a5-8220-e606a16e63b0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzNjkzMjgsIm5iZiI6MTcxNjM2OTAyOCwicGF0aCI6Ii8xMTgwNzkzLzMzMjY0NTI4Mi1mODA2NGIxNi1jODhjLTQ5YTUtODIyMC1lNjA2YTE2ZTYzYjAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjJUMDkxMDI4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9N2EyMmM1NWMyZjYxODMyMGNlOGQyZTgyNjI2Y2Q1YzFjOGI2MzVjOTFhNDkxZmIxZTk0MzJmZTM4ODI4Y2VkOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.iwF4O1roGQUoOxQvKCPb6lK0IJkV8fKvZHISDo1IoKo)
> 
> ![企业微信截图_1fe64ef1-95b8-412b-b2b7-937ecbe71fe0](https://private-user-images.githubusercontent.com/1180793/332645419-1fa13493-5345-4d30-ba6e-b8908f67d247.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzNjkzMjgsIm5iZiI6MTcxNjM2OTAyOCwicGF0aCI6Ii8xMTgwNzkzLzMzMjY0NTQxOS0xZmExMzQ5My01MzQ1LTRkMzAtYmE2ZS1iODkwOGY2N2QyNDcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjJUMDkxMDI4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZThkZGJhODlmNmE4MGY5MjBiMzU1MzU5YWE2YWZmNDc1MmM4MGRlOTFmMDIwODhjNTY1N2FhYmQzYmM1ZmQ0MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.JpqjWWgYwfgcHBRBKHc1ufoFMMZZI84BpkEWFRdPRqQ)

我测试也是这样的。当前的方案对这种场景会有问题，我来想想如何解决。

**Comment by jersy** [comment]
> > @mainmainer 最终执行的sql不对，应该取当天所有部门里访问量最大的部门， 最终sql按 sys_imp_date,department进行分组，变成了每个部门当天最大访问次数了。 我用的默认数据集进行测试的，你可以在你本地进行一下测试
> > ![企业微信截图_69f47127-8b17-43a9-9afb-aeae5cf9d775](https://private-user-images.githubusercontent.com/1180793/332645282-f8064b16-c88c-49a5-8220-e606a16e63b0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzNjkzMjgsIm5iZiI6MTcxNjM2OTAyOCwicGF0aCI6Ii8xMTgwNzkzLzMzMjY0NTI4Mi1mODA2NGIxNi1jODhjLTQ5YTUtODIyMC1lNjA2YTE2ZTYzYjAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjJUMDkxMDI4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9N2EyMmM1NWMyZjYxODMyMGNlOGQyZTgyNjI2Y2Q1YzFjOGI2MzVjOTFhNDkxZmIxZTk0MzJmZTM4ODI4Y2VkOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.iwF4O1roGQUoOxQvKCPb6lK0IJkV8fKvZHISDo1IoKo)
> > ![企业微信截图_1fe64ef1-95b8-412b-b2b7-937ecbe71fe0](https://private-user-images.githubusercontent.com/1180793/332645419-1fa13493-5345-4d30-ba6e-b8908f67d247.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzNjkzMjgsIm5iZiI6MTcxNjM2OTAyOCwicGF0aCI6Ii8xMTgwNzkzLzMzMjY0NTQxOS0xZmExMzQ5My01MzQ1LTRkMzAtYmE2ZS1iODkwOGY2N2QyNDcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjJUMDkxMDI4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZThkZGJhODlmNmE4MGY5MjBiMzU1MzU5YWE2YWZmNDc1MmM4MGRlOTFmMDIwODhjNTY1N2FhYmQzYmM1ZmQ0MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.JpqjWWgYwfgcHBRBKHc1ufoFMMZZI84BpkEWFRdPRqQ)
> 
> 我测试也是这样的。当前的方案对这种场景会有问题，我来想想如何解决。

👍

**Comment by jerryjzhang** [comment]
测试了几个大模型(gpt-3.5-turbo, gpt-4-0125-preview, gpt-4o, moonshot-v1-8k, deepseek-coder, glm-4, qwen-turbo)。目前看来，gpt-4和glm-4给出的SQL结果还是比较靠谱，其他差很远。这个问题实际上比较复杂了，涉及分组、排序和窗口。当前，这么复杂的SQL，在supersonic语义层还不太支持，需要后续来优化解析能力。


以下是gpt-4的输出结果：
> Final Answer: sql=[SELECT 日期, 部门, 访问次数 FROM (SELECT 日期, 部门, 访问次数, ROW_NUMBER() OVER(PARTITION BY 日期 ORDER BY 访问次数 DESC) AS rank FROM (SELECT DATE_FORMAT(时间, 'YYYYMMDD') AS 日期, 部门, COUNT(*) AS 访问次数 FROM 内容库埋点数据集 WHERE DATE_FORMAT(时间, 'YYYYMMDD') BETWEEN '20240513' AND '20240522' GROUP BY 日期, 部门) AS temp) AS ranked WHERE rank = 1]`

以下是glm-4的输出结果：
> Final Answer: sql=SELECT 部门, 访问次数, 记录日期 FROM (SELECT 部门, COUNT(*) AS 访问次数, 记录日期, ROW_NUMBER() OVER (PARTITION BY 记录日期 ORDER BY COUNT(*) DESC) AS rn FROM 内容库埋点数据集 WHERE 记录日期 BETWEEN '20240513' AND '20240522' GROUP BY 部门, 记录日期) t WHERE t.rn = 1 ORDER BY 记录日期;
> 这个SQL语句首先通过WHERE子句限定记录日期在最近10天内，然后按部门和记录日期进行分组，计算每天的访问次数，接着使用ROW_NUMBER()窗口函数为每个记录日期内的部门访问次数排序，并给每组分配一个行号（rn），最后在外层查询中筛选出行号为1的记录，即每个记录日期下访问次数最多的部门。最后按记录日期排序，展示结果。

**Comment by jersy** [comment]
> 测试了几个大模型(gpt-3.5-turbo, gpt-4-0125-preview, gpt-4o, moonshot-v1-8k, deepseek-coder, glm-4, qwen-turbo)。目前看来，gpt-4和glm-4给出的SQL结果还是比较靠谱，其他差很远。这个问题实际上比较复杂了，涉及分组、排序和窗口。当前，这么复杂的SQL，在supersonic语义层还不太支持，需要后续来优化解析能力。
> 
> 以下是gpt-4的输出结果：
> 
> > Final Answer: sql=[SELECT 日期, 部门, 访问次数 FROM (SELECT 日期, 部门, 访问次数, ROW_NUMBER() OVER(PARTITION BY 日期 ORDER BY 访问次数 DESC) AS rank FROM (SELECT DATE_FORMAT(时间, 'YYYYMMDD') AS 日期, 部门, COUNT(*) AS 访问次数 FROM 内容库埋点数据集 WHERE DATE_FORMAT(时间, 'YYYYMMDD') BETWEEN '20240513' AND '20240522' GROUP BY 日期, 部门) AS temp) AS ranked WHERE rank = 1]`
> 
> 以下是glm-4的输出结果：
> 
> > Final Answer: sql=SELECT 部门, 访问次数, 记录日期 FROM (SELECT 部门, COUNT(_) AS 访问次数, 记录日期, ROW_NUMBER() OVER (PARTITION BY 记录日期 ORDER BY COUNT(_) DESC) AS rn FROM 内容库埋点数据集 WHERE 记录日期 BETWEEN '20240513' AND '20240522' GROUP BY 部门, 记录日期) t WHERE t.rn = 1 ORDER BY 记录日期;
> > 这个SQL语句首先通过WHERE子句限定记录日期在最近10天内，然后按部门和记录日期进行分组，计算每天的访问次数，接着使用ROW_NUMBER()窗口函数为每个记录日期内的部门访问次数排序，并给每组分配一个行号（rn），最后在外层查询中筛选出行号为1的记录，即每个记录日期下访问次数最多的部门。最后按记录日期排序，展示结果。

谢谢大佬回复。

那现在有什么方法能达成这个指标查询吗？ 我在语义模型定义一个指标，就能查询到吗？
另外除了分组、排序和窗口这种复杂的sql，还有其他限制没？

**Comment by jerryjzhang** [comment]
> > 测试了几个大模型(gpt-3.5-turbo, gpt-4-0125-preview, gpt-4o, moonshot-v1-8k, deepseek-coder, glm-4, qwen-turbo)。目前看来，gpt-4和glm-4给出的SQL结果还是比较靠谱，其他差很远。这个问题实际上比较复杂了，涉及分组、排序和窗口。当前，这么复杂的SQL，在supersonic语义层还不太支持，需要后续来优化解析能力。
> > 以下是gpt-4的输出结果：
> > > Final Answer: sql=[SELECT 日期, 部门, 访问次数 FROM (SELECT 日期, 部门, 访问次数, ROW_NUMBER() OVER(PARTITION BY 日期 ORDER BY 访问次数 DESC) AS rank FROM (SELECT DATE_FORMAT(时间, 'YYYYMMDD') AS 日期, 部门, COUNT(*) AS 访问次数 FROM 内容库埋点数据集 WHERE DATE_FORMAT(时间, 'YYYYMMDD') BETWEEN '20240513' AND '20240522' GROUP BY 日期, 部门) AS temp) AS ranked WHERE rank = 1]`
> > 
> > 
> > 以下是glm-4的输出结果：
> > > Final Answer: sql=SELECT 部门, 访问次数, 记录日期 FROM (SELECT 部门, COUNT(_) AS 访问次数, 记录日期, ROW_NUMBER() OVER (PARTITION BY 记录日期 ORDER BY COUNT(_) DESC) AS rn FROM 内容库埋点数据集 WHERE 记录日期 BETWEEN '20240513' AND '20240522' GROUP BY 部门, 记录日期) t WHERE t.rn = 1 ORDER BY 记录日期;
> > > 这个SQL语句首先通过WHERE子句限定记录日期在最近10天内，然后按部门和记录日期进行分组，计算每天的访问次数，接着使用ROW_NUMBER()窗口函数为每个记录日期内的部门访问次数排序，并给每组分配一个行号（rn），最后在外层查询中筛选出行号为1的记录，即每个记录日期下访问次数最多的部门。最后按记录日期排序，展示结果。
> 
> 谢谢大佬回复。
> 
> 那现在有什么方法能达成这个指标查询吗？ 我在语义模型定义一个指标，就能查询到吗？ 另外除了分组、排序和窗口这种复杂的sql，还有其他限制没？

目前来看不太行，可能拆成多个SQL分步骤来行更靠谱一点。不过这个能力我们内部在验证和迭代，短期内不太会开源出来。

**Comment by jersy** [comment]
> > > 测试了几个大模型(gpt-3.5-turbo, gpt-4-0125-preview, gpt-4o, moonshot-v1-8k, deepseek-coder, glm-4, qwen-turbo)。目前看来，gpt-4和glm-4给出的SQL结果还是比较靠谱，其他差很远。这个问题实际上比较复杂了，涉及分组、排序和窗口。当前，这么复杂的SQL，在supersonic语义层还不太支持，需要后续来优化解析能力。
> > > 以下是gpt-4的输出结果：
> > > > Final Answer: sql=[SELECT 日期, 部门, 访问次数 FROM (SELECT 日期, 部门, 访问次数, ROW_NUMBER() OVER(PARTITION BY 日期 ORDER BY 访问次数 DESC) AS rank FROM (SELECT DATE_FORMAT(时间, 'YYYYMMDD') AS 日期, 部门, COUNT(*) AS 访问次数 FROM 内容库埋点数据集 WHERE DATE_FORMAT(时间, 'YYYYMMDD') BETWEEN '20240513' AND '20240522' GROUP BY 日期, 部门) AS temp) AS ranked WHERE rank = 1]`
> > > 
> > > 
> > > 以下是glm-4的输出结果：
> > > > Final Answer: sql=SELECT 部门, 访问次数, 记录日期 FROM (SELECT 部门, COUNT(_) AS 访问次数, 记录日期, ROW_NUMBER() OVER (PARTITION BY 记录日期 ORDER BY COUNT(_) DESC) AS rn FROM 内容库埋点数据集 WHERE 记录日期 BETWEEN '20240513' AND '20240522' GROUP BY 部门, 记录日期) t WHERE t.rn = 1 ORDER BY 记录日期;
> > > > 这个SQL语句首先通过WHERE子句限定记录日期在最近10天内，然后按部门和记录日期进行分组，计算每天的访问次数，接着使用ROW_NUMBER()窗口函数为每个记录日期内的部门访问次数排序，并给每组分配一个行号（rn），最后在外层查询中筛选出行号为1的记录，即每个记录日期下访问次数最多的部门。最后按记录日期排序，展示结果。
> > 
> > 
> > 谢谢大佬回复。
> > 那现在有什么方法能达成这个指标查询吗？ 我在语义模型定义一个指标，就能查询到吗？ 另外除了分组、排序和窗口这种复杂的sql，还有其他限制没？
> 
> 目前来看不太行，可能拆成多个SQL分步骤来行更靠谱一点。不过这个能力我们内部在验证和迭代，短期内不太会开源出来。

好的，期待大佬早日开源

另外我刚刚下了最新的代码，试了一下“对比alice和lucy的访问次数”问题，貌似报错了。

**Comment by mainmainer** [comment]
> ROW_NUMBER() OVER(PARTITION BY 日期 ORDER BY 访问次数 DESC)

得生成一个：SELECT 数据日期, 部门,访问次数 from (
SELECT 数据日期, 部门,访问次数,ROW_NUMBER() OVER(PARTITION BY 日期 ORDER BY 访问次数 DESC) as rank  from (

SELECT 数据日期, 部门, sum(访问次数) as 访问次数  FROM 超音数 WHERE datediff('day', 数据日期, '2024-05-17') <= 10 GROUP BY 数据日期, 部门)

) where rank=1
这种类似的SQL才行
