### ISSUE TITLE
执行 “对比alice和lucy的访问次数”报错

### ISSUE THREAD

**Issue by jersy** [tencentmusic/supersonic#1027]
在最新的master执行 “对比alice和lucy的访问次数”存在问题。

@mainmainer @jerryjzhang 麻烦两位大佬看看

![image](https://github.com/tencentmusic/supersonic/assets/1180793/6d3aa4ae-d483-442b-86db-84e8c1b773d4)

![image](https://github.com/tencentmusic/supersonic/assets/1180793/2c238422-f85e-4ad2-94ca-863fba38cdfb)

![image](https://github.com/tencentmusic/supersonic/assets/1180793/3b0ecdfe-4e36-4786-afb7-6f9a637ca5e3)

![image](https://github.com/tencentmusic/supersonic/assets/1180793/2e9ffaf1-9c0f-4cc8-9605-4eea5c540054)

最终执行代码

`SELECT
  *
FROM
  (
    with t_1 as (
      SELECT
        `imp_date` AS `sys_imp_date`,
        `user_name`,
        SUM(1) AS `pv`
      FROM
        `s2_pv_uv_statis`
      GROUP BY
        `imp_date`,
        `user_name`,
        `imp_date`
    )
    SELECT
      user_name,
      SUM(pv),
      sys_imp_date
    FROM
      t_1
    WHERE
      (
        user_name = 'alice'
        OR user_name = 'lucy'
      )
      AND sys_imp_date = '2024-05-22'
    GROUP BY
      user_name,
      sys_imp_date
  ) a
LIMIT
  1000`

**Comment by jersy** [comment]
jsqlparser 解析sql异常

![image](https://github.com/tencentmusic/supersonic/assets/1180793/0b3eaa71-293d-45c4-a89a-b91d3861819b)

**Comment by mainmainer** [comment]
好的，收到，会尽快处理

**Comment by jerryjzhang** [comment]
> 在最新的master执行 “对比alice和lucy的访问次数”存在问题。
> 
> @mainmainer @jerryjzhang 麻烦两位大佬看看
> 
> ![image](https://private-user-images.githubusercontent.com/1180793/332784125-6d3aa4ae-d483-442b-86db-84e8c1b773d4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2NDI0NDgsIm5iZiI6MTcxNzY0MjE0OCwicGF0aCI6Ii8xMTgwNzkzLzMzMjc4NDEyNS02ZDNhYTRhZS1kNDgzLTQ0MmItODZkYi04NGU4YzFiNzczZDQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MDZUMDI0OTA4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDg0YjViNDQyNjU4YmViNWM4N2Y0NzUyMTlmMDM3YTE5MTY4ODc2MGFjYTM5OGE5ODhmZDg5ODVhNTg4MjMyYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.X_I1JE5GVKrtvLkQ6KRwFQ07Kxh5qqQWikOO5eYpUZM)
> 
> ![image](https://private-user-images.githubusercontent.com/1180793/332784213-2c238422-f85e-4ad2-94ca-863fba38cdfb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2NDI0NDgsIm5iZiI6MTcxNzY0MjE0OCwicGF0aCI6Ii8xMTgwNzkzLzMzMjc4NDIxMy0yYzIzODQyMi1mODVlLTRhZDItOTRjYS04NjNmYmEzOGNkZmIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MDZUMDI0OTA4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzliMGY5MDdkNTgwZTQ2ZGYwY2M1NTQyZjNiMmYxOWE0ZGZlNDBhYjNjYjYyNjNjMmU0NzViZjc4NTBjZjcwNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.yXKAFjTvM0Wn8NxFBHqvesDX6d37Vku2EOKrjVFEcvY)
> 
> ![image](https://private-user-images.githubusercontent.com/1180793/332784328-3b0ecdfe-4e36-4786-afb7-6f9a637ca5e3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2NDI0NDgsIm5iZiI6MTcxNzY0MjE0OCwicGF0aCI6Ii8xMTgwNzkzLzMzMjc4NDMyOC0zYjBlY2RmZS00ZTM2LTQ3ODYtYWZiNy02ZjlhNjM3Y2E1ZTMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MDZUMDI0OTA4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmMyY2EyYmJmMGRmY2ZmZDEwNzZiOGMzODhmYzJjYzBkOWU4YzBhZTNiODU0OGI2ZjUyNDI2MjA4NWIxM2RhOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.rAtKQ4zb9esablImOOmF9tDYlRxwNpp-Hy5JEuPQBYg)
> 
> ![image](https://private-user-images.githubusercontent.com/1180793/332784448-2e9ffaf1-9c0f-4cc8-9605-4eea5c540054.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2NDI0NDgsIm5iZiI6MTcxNzY0MjE0OCwicGF0aCI6Ii8xMTgwNzkzLzMzMjc4NDQ0OC0yZTlmZmFmMS05YzBmLTRjYzgtOTYwNS00ZWVhNWM1NDAwNTQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MDZUMDI0OTA4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDQyMmY3NGQwOTkxM2Q0ZTAyNDUyODI4YWQxMTZlZGI0YTlhYzAyZDQwZWFhMjU1YjBjMjJlYjk3NjRjZDg0MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.UHkOvo49chccEoWfs5_6Dgvm8SNL7OqwteVArBl3ObU)
> 
> 最终执行代码
> 
> `SELECT * FROM ( with t_1 as ( SELECT `imp_date`AS`sys_imp_date`, `user_name`, SUM(1) AS `pv`FROM`s2_pv_uv_statis`GROUP BY`imp_date`, `user_name`, `imp_date` ) SELECT user_name, SUM(pv), sys_imp_date FROM t_1 WHERE ( user_name = 'alice' OR user_name = 'lucy' ) AND sys_imp_date = '2024-05-22' GROUP BY user_name, sys_imp_date ) a LIMIT 1000`

这里其实不是SQL生成的问题，是因为DEMO数据里缺少最新这一天的数据
