### ISSUE TITLE
如何自定义自己的数据

### ISSUE THREAD

**Issue by godlovefei** [tencentmusic/supersonic#1028]
您好！ 对java不是很在行，在部署完成后在界面一系列操作，结果一重启服务都没了。看了下java的一些源代码，我看界面的一些操作在standalone中写死了。

想咨询下如何使用自己的数据呢？给一点点思路，感激莫名

**Comment by jersy** [comment]
默认用的H2数据库，是内存数据库，重启后就丢了。

把这里改成mysql，具体怎么改可以在网上搜一下

![image](https://github.com/tencentmusic/supersonic/assets/1180793/9fcd63fe-7da1-43ea-aa05-d8884426a4b5)

**Comment by lexluo09** [comment]
https://github.com/tencentmusic/supersonic/wiki/%E6%9E%84%E5%BB%BA%E5%92%8C%E5%90%AF%E5%8A%A8
系统默认对h2数据库支持样例数据, 若需要基于本地mysql查看样例数据, 可执行schema-mysql.sql来创建最新表结构, 并执行data-mysql.sql把样例数据写入mysql, 之后系统在启动的时候会自动把系统元数据和会话数据写入mysql表,系统启动成功后可在页面看到样例数据, 详细可参考DemoLoader。若需要从h2切换至mysql, 按如下正常配置即可

<img width="980" alt="image" src="https://github.com/tencentmusic/supersonic/assets/39718951/f85f5748-7ee3-48e4-a6c0-eec652d13d09">

**Comment by godlovefei** [comment]
Done
