### ISSUE TITLE
Chat Plugin功能一直无法命中

### ISSUE THREAD

**Issue by godlovefei** [tencentmusic/supersonic#1055]

**Comment by lxwcodemonkey** [comment]
可以尝试建一个新的助理，然后把系统内置的插件加入到这个助理工具中试试~
![image](https://github.com/tencentmusic/supersonic/assets/22031277/b8abfc9f-2d63-4dad-b30d-ca7abcdd04c7)
旧版代码在插件上设置了参数，需要从用户文本中识别到参数值才能成功召回(如tom访问情况，可以从文本中识别到用户名=tom)，最新代码为了样例能够更容易召回，把参数前置条件去掉了

**Comment by godlovefei** [comment]
我想创建使用自己的插件，但是使用示例的貌似也没法命中
![image](https://github.com/tencentmusic/supersonic/assets/33597028/2a08631f-4c7d-41d0-911b-7ae422e17471)
![image](https://github.com/tencentmusic/supersonic/assets/33597028/1a575d0f-9583-4ea5-aef1-9439f3b92d7b)
@lxwcodemonkey

**Comment by lxwcodemonkey** [comment]
可以看一下这个助理的配置不

**Comment by godlovefei** [comment]
![image](https://github.com/tencentmusic/supersonic/assets/33597028/5605dfa5-9abb-4e55-834d-a695fb17260e)
自带插件示例
@lxwcodemonkey

**Comment by lxwcodemonkey** [comment]
可能是没有识别到插件需要的参数值，是否已经把用户这个维度已经删掉了？可以把插件上配置的参数先去掉，或者拉新一点的代码，新的代码把参数去掉了，去掉原因上面有提到

**Comment by lxwcodemonkey** [comment]
@godlovefei 这边目前怎么样了呢

**Comment by godlovefei** [comment]
不好意思哈前段时间忘记回了，还是无法命中呢@lxwcodemonkey
