### ISSUE TITLE
线上体验环境

### ISSUE THREAD

**Issue by dawsongzhao0523** [tencentmusic/supersonic#1075]
提供线上体验环境：http://117.72.46.148:9080
建议：修改当前登陆框中的用户名/密码提示，创建一个新的体验账号

**Comment by mobguang** [comment]
线上体验环境down了，请问能恢复吗，谢谢。

**Comment by dawsongzhao0523** [comment]
> 线上体验环境down了，请问能恢复吗，谢谢。

已恢复，这边配置一个定时重启机制

**Comment by mobguang** [comment]
还是打不开......
![image](https://github.com/tencentmusic/supersonic/assets/519028/01f5fba1-15f4-4424-a928-f606bf722ad8)

**Comment by dawsongzhao0523** [comment]
已使用supervisor自动重启，解决内存不足导致oom killer问题
