### ISSUE TITLE
【问答对话】使用demo库，第一次问答走LLM，第二次问答走rule，这个是为啥？

### ISSUE THREAD

**Issue by dawsongzhao0523** [tencentmusic/supersonic#1079]
## 前端现象
![第一次测试为llm，第二次为rule](https://github.com/tencentmusic/supersonic/assets/133857587/efa464fe-d430-4813-b296-39c02d2b517a)
## 执行日志
[正常执行查询的日志.log](https://github.com/user-attachments/files/15525547/default.log)

**Comment by lxwcodemonkey** [comment]
这好像全都是走的大模型？

**Comment by mainmainer** [comment]
都是走的大模型
