### ISSUE TITLE
【问答对话】当问答内容LLM无法maper到语义模型字段时，直接返回：智能助理不太懂您说什么呐，回去一定补充知识

### ISSUE THREAD

**Issue by dawsongzhao0523** [tencentmusic/supersonic#1080]
## 问题：
当问答内容LLM无法maper到语义模型字段时，直接返回：智能助理不太懂您说什么呐，回去一定补充知识
例如：
demo库问答：查询所有明细数据
返回：智能助理不太懂您说什么呐，回去一定补充知识
## 期望：
1、猜测用户查询意图，你是要查询xxx模型的所有字段么？
2、或者引导用户提问，例如，请查询艺人库所有区域的数据

**Comment by jerryjzhang** [comment]
这个建议不错，可以计划来实现

**Comment by jerryjzhang** [comment]
补充一个点，除了告诉用户有哪些元数据之外，可以通过成功案例来做提示引导
