### ISSUE TITLE
更多模型的支持

### ISSUE THREAD

**Issue by shanmu-raoyunfei** [tencentmusic/supersonic#1086]
除了OpenAI，可以支持更多的商业化或者开源模型吗？

**Comment by lxwcodemonkey** [comment]
现在常见的一些模型应该都是兼容OPENAI协议的，这边是需要用到什么模型呢

**Comment by Shame-fight** [comment]
> 现在常见的一些模型应该都是兼容OPENAI协议的，这边是需要用到什么模型呢

请问如何接入百度千帆ERNIE-4.0系列模型 @lxwcodemonkey

**Comment by jerryjzhang** [comment]
千帆的目前还没有测试过，DeepSeek、Qwen、Moonshot、GLM这几个目前都测试过，它们的API是兼容open_ai接口协议的
