### ISSUE TITLE
【术语管理】支持在创建术语时关联指标/维度

### ISSUE THREAD

**Issue by lxwcodemonkey** [tencentmusic/supersonic#1089]
举个例子，比如创建了一个叫做“热歌”的术语，”热歌“的含义是播放量大于100000的歌曲，但是如果用户直接询问”xxx的热歌“，Mapper可能无法从文本中map出播放量这个指标，所以给到LLM的前置知识就会缺失这个指标，导致大模型即便知道”热歌“指代的含义，但也无法得到具体的播放量指标，因此需要支持在创建术语时关联指标/维度

**Comment by jerryjzhang** [comment]
#1462 规划对术语描述进行语义检索，自动提取相关的语义实体，所以不再需要创建术语时手动去关联，降低使用成本
