### ISSUE TITLE
接入文心一言在线模型ernie-4.0-8k-0329无效

### ISSUE THREAD

**Issue by Shame-fight** [tencentmusic/supersonic#1092]
您好，感谢您的代码。我想使用该仓库代码用在私有数据集上，但貌似不起作用。
我需要使用国产百度ERNIE-4.0-8K-0329在线api,做的修改如下：
1. supersonic-standalone-0.9.2-SNAPSHOT/pyllm/config/run_config.ini：
`[LLMProvider]
LLM_PROVIDER_NAME = openai

[LLMModel]
OPENAI_API_KEY = okok
OPENAI_API_BASE = https://aip.baidubce.com/rpc/2.0/ai_custom/v1/wenxinworkshop/chat/ernie-4.0-8k-0329?access_token=[通过api key和secret key获得的token]
MODEL_NAME = ernie-4.0
TEMPERATURE = 0.7`

2. sh supersonic-daemon.sh restart
但并没有起作用，是否配置文件修改方式有问题，请问如何解决

**Comment by jerryjzhang** [comment]
你好，尝试下再助理中配置大模型试试

**Comment by mainmainer** [comment]
我这两天尽快看下

**Comment by mainmainer** [comment]
> 您好，感谢您的代码。我想使用该仓库代码用在私有数据集上，但貌似不起作用。 我需要使用国产百度ERNIE-4.0-8K-0329在线api,做的修改如下：
> 
> 1. supersonic-standalone-0.9.2-SNAPSHOT/pyllm/config/run_config.ini：
>    `[LLMProvider]
>    LLM_PROVIDER_NAME = openai
> 
> [LLMModel] OPENAI_API_KEY = okok OPENAI_API_BASE = [https://aip.baidubce.com/rpc/2.0/ai_custom/v1/wenxinworkshop/chat/ernie-4.0-8k-0329?access_token=[通过api](https://aip.baidubce.com/rpc/2.0/ai_custom/v1/wenxinworkshop/chat/ernie-4.0-8k-0329?access_token=%5B%E9%80%9A%E8%BF%87api) key和secret key获得的token] MODEL_NAME = ernie-4.0 TEMPERATURE = 0.7`
> 
> 2. sh supersonic-daemon.sh restart
>    但并没有起作用，是否配置文件修改方式有问题，请问如何解决

这个不符合openai协议，得先用ak和sk生成token，再请求。

**Comment by xiaodin1** [comment]
后续有支持文心、千问、KIMI、豆包等国内大模型吗?
https://github.com/langchain4j/langchain4j/pull/499/files/176a235f18e3d3be2cd3a4556508ea50ceda1e79..dd8c3f90f444f52e88becf6c9a6767ca3e59a10d#diff-8a87155620a985d6ba47960d9a91bfff98dcba9984d72ccc517d374ca90600f8
