### ISSUE TITLE
execute接口返回包括LLM明文信息

### ISSUE THREAD

**Issue by lcp5674** [tencentmusic/supersonic#1094]
在调用/api/chat/query/execute查询接口返回结果中包含LLM配置明文信息，建议将其加密或不返回
![image](https://github.com/tencentmusic/supersonic/assets/24891144/44d987ac-68ed-4417-8284-118497af86f3)

**Comment by jerryjzhang** [comment]
感谢建议，安排优化

**Comment by lxwcodemonkey** [comment]
放到这个issue来处理了https://github.com/tencentmusic/supersonic/issues/1076
