### ISSUE TITLE
【助理管理】新增工具，提示保存成功，但是看不到工具列表。F12查看，提示JSON parse error: parseLong error, value : DOMAIN_11;

### ISSUE THREAD

**Issue by dawsongzhao0523** [tencentmusic/supersonic#1100]
![image](https://github.com/tencentmusic/supersonic/assets/133857587/f73c361c-9567-4931-8324-1cb0bebf155e)

跟踪代码，定位到问题：
![image](https://github.com/tencentmusic/supersonic/assets/133857587/7962710d-25c0-4c34-ade3-297f70de8ae3)
点击目录【Dify运营数据】 域下面 没有数据集，但是已经有：子目录：访问数据

这里交互有些费解。

**Comment by dawsongzhao0523** [comment]
解决方案：新建工具时，如果目录下没有数据集，就不能选择目录创建工具
![image](https://github.com/tencentmusic/supersonic/assets/133857587/e8785bf9-909d-4f0d-8386-3182adfd1853)

**Comment by lxwcodemonkey** [comment]
已解决 后端过滤模型集 且0.9.4已去掉模型集
