### ISSUE TITLE
[Feature]【语义建模】导入维度值后，支持查看维度值详情，支持过滤选择维度值，配置黑白名单

### ISSUE THREAD

**Issue by dawsongzhao0523** [tencentmusic/supersonic#1121]
## 问题
![image](https://github.com/tencentmusic/supersonic/assets/133857587/07cba70a-5081-4cc9-a523-757163434a11)

## 建议
导入成功后，在导入界面支持查看导入的维度值字典详情。

**Comment by dawsongzhao0523** [comment]
维度字典 ，如果不在数据库。迫切需要一个界面可以查看 最简单的实现 就是支持上传下载，让普通管理员可以查看、操作。
只有超级管理员，能够控制服务器的人 ，才能查看定位问题。

**Comment by jerryjzhang** [comment]
导入成功的维度值，最好是在维度管理的界面上可以展示，便于管理员查看具体的维度值 @daikon12

**Comment by daikon12** [comment]
https://github.com/tencentmusic/supersonic/pull/1196
可以看看这个是否能满足需求哈
