### ISSUE TITLE
【问答对话】维度值提示，补充提示类别，XXX表，xxx维度，维度值：

### ISSUE THREAD

**Issue by dawsongzhao0523** [tencentmusic/supersonic#1125]
## 问题
![image](https://github.com/tencentmusic/supersonic/assets/133857587/6d9b67b6-cfaa-402c-b017-38c2297a97a6)

不清楚【02】这个维度值，对应哪个【维度】给用户困惑。

## 期望
术语，维度、指标的提示的时候，能够准确的知道是什么术语、维度、指标名的提示。

**Comment by jerryjzhang** [comment]
维度值前加对应的维度，在前期版本中应该是支持的， @williamhliu 看看是不是需要恢复或者重新加上

**Comment by dawsongzhao0523** [comment]
社区以实现，指标、维度、维度值、术语的提示
