### ISSUE TITLE
修改 前端根目录webapp下面的 packages/chat-sdk 里面的前端文件，页面无法更新

### ISSUE THREAD

**Issue by php19850120** [tencentmusic/supersonic#1126]
修改 前端根目录webapp下面的 packages/chat-sdk 里面的前端文件，本地执行start-fe-dev.bat命令，页面无法更新。一直访问的都是修改之前的页面。查看chat-sdk 里面的dist文件，已经更行了，但是本地访问还是修改前的页面。

**Comment by sevenliu1896** [comment]
#1127 中提交了新的启动模式，使用pnpm workspace替代对原来pnpm link的启动模式
核心关注点如下：
1.建立对chat工程的编译watch
![image](https://github.com/tencentmusic/supersonic/assets/37809633/06fce874-7d49-450a-b37d-68f24c04f766)

2.supersonic-fe工程的packages.json中将chat版本号更新为"workspace:*“
![image](https://github.com/tencentmusic/supersonic/assets/37809633/e0eddd01-5adc-48f9-84fa-60d1a5f3265e)

3.更新supersonic-fe工程中umi的config文件，使chat热更新生效
![image](https://github.com/tencentmusic/supersonic/assets/37809633/28dafa7a-295d-4bc2-89d4-88759852f671)

4.增加start-fe-pnpm-workspace-dev.bat,start-fe-pnpm-workspace-dev.sh新模式的启动脚本
