### ISSUE TITLE
【问答对话】问答性能优化

### ISSUE THREAD

**Issue by dawsongzhao0523** [tencentmusic/supersonic#1131]
## 问题
![image](https://github.com/tencentmusic/supersonic/assets/133857587/87632969-e5b3-4622-a2ee-0538f61dcb2a)
目前，意图识别、解析及查询时间蛮长。性能不足。
<img width="916" alt="image" src="https://github.com/tencentmusic/supersonic/assets/133857587/7ad3b3c3-e34e-4312-9a49-3eb59a4651f3">
查看代码，parser执行了一些search执行过的逻辑。execute又执行了一些parser和search的逻辑，重复的逻辑是否可以缓存复用
## 期望
执行一次查询在5s内 返回数据

**Comment by jerryjzhang** [comment]
整个pipeline确实有优化的空间，不过目前开销最大的阶段还是大模型解析，可以考虑切换推理更快的模型服务，比如gpt-4o, gpt-3.5

**Comment by dawsongzhao0523** [comment]
> 整个pipeline确实有优化的空间，不过目前开销最大的阶段还是大模型解析，可以考虑切换推理更快的模型服务，比如gpt-4o, gpt-3.5

我们使用的gpt-4o, gpt-3.5做的测试。内部通过APM监控了系统运行的情况，发现了较多数据库io操作。以及较多全“语义模型”、数据集、维度及指标扫描查找的操作。如果接入的语义模型、指标、维度多了，应该会有较多性能瓶颈。在思考通过逻辑重构、缓存等方式优化性能问题。

**Comment by lxwcodemonkey** [comment]
仔细看了下 之前buildParseContext方法中有进行map 可能会有一点耗时，现已优化，buildParseContext基本只有一些对象copy和逻辑判断等操作，应该基本无耗时了

**Comment by lxwcodemonkey** [comment]
较多数据库io操作。以及较多全“语义模型”、数据集、维度及指标扫描查找的操作
这个我们看看优化下
