### ISSUE TITLE
【权限管理】增加行权限配置说明，或者提供快捷配置方式

### ISSUE THREAD

**Issue by dawsongzhao0523** [tencentmusic/supersonic#1146]
<img width="1350" alt="image" src="https://github.com/tencentmusic/supersonic/assets/133857587/fa3c657b-a0c6-4065-bad6-28a42ce82980">

**Comment by jerryjzhang** [comment]
届时会在文档中心中补充相应的说明

**Comment by lxwcodemonkey** [comment]
已补充说明到文档中心
https://supersonicbi.github.io/docs/headless-bi/%E9%85%8D%E7%BD%AE%E6%95%B0%E6%8D%AE%E6%9D%83%E9%99%90/
