### ISSUE TITLE
【开发工具】增加mybatis CURD的代码生成工具

### ISSUE THREAD

**Issue by dawsongzhao0523** [tencentmusic/supersonic#1147]
增加mybatis CURD的代码生成工具，现在开发操作数据库表的流程需要增加较多代码，开发耗时。

**Comment by lxwcodemonkey** [comment]
现在是使用的mybatis-plus，CURD可以直接调底层方法的，还是说觉得mybatis-plus也太麻烦了

**Comment by dawsongzhao0523** [comment]
指的是要写较多的pojo do service reposity等

**Comment by lexluo09** [comment]
很好的想法，我们有其他项目也增加mybatis-plus的代码生成工具，可以提高开发效率；如果有兴趣的话，欢迎贡献PR

**Comment by dawsongzhao0523** [comment]
周末调研了一下，以下 idea插件都能达到类似的效果：
  - EasyCode
  - MybatisX：初步调研，个人使用改插件。后续有官方开发指南了，个人可提供相关使用文档。
  - mybatis-sql-viewer
  - MybatisPlus
