### ISSUE TITLE
请问最新开源的qwen2-70B可否用来替换

### ISSUE THREAD

**Issue by Spider4U** [tencentmusic/supersonic#1151]
![image](https://github.com/tencentmusic/supersonic/assets/39551480/e8c0b284-4b85-40f1-a434-870d94b96cfc)

请问qwen2-70B测试有效果嘛

**Comment by jerryjzhang** [comment]
可以的，我们使用qwen模型服务验证过，效果还是可以的

**Comment by mainmainer** [comment]
我当时用qwen-max效果还可以的，可以试试
