### ISSUE TITLE
【问答对话】增加Text2SQL评测用例

### ISSUE THREAD

**Issue by jerryjzhang** [tencentmusic/supersonic#1152]
###说明

设计一组测试用例，当提示词策略出现迭代，或者切换不同的大模型时，校验Text2SQL查询结果的准确性。

**Comment by dawsongzhao0523** [comment]
这个提议很棒，我这边也在做类似的事情

**Comment by jerryjzhang** [comment]
已经初步提交了一版

**Comment by dawsongzhao0523** [comment]
> 已经初步提交了一版

嗯嗯，提供接口，支持社区大家不断提供自己的数据集，做一个测评仓库。这一块业界都比较缺。
