### ISSUE TITLE
增加对多数据源的支持，诸如：oracle、hive、hbase、redis等

### ISSUE THREAD

**Issue by wap1990-0903** [tencentmusic/supersonic#1160]
目前支持的开源数据库较少，oracle、reids、clickhouse等均不支持，希望能在下个版本中增加对开源数据库的支持。

**Comment by dawsongzhao0523** [comment]
clickhouse是支持的使用mysql协议连接即可。
理论上，目前支持mysql语法的数据库，例如mysql、clickhouse、doris、Starrocks、DuckDB；支持Postgresql语法的数据库，例如Postgresql、RsingWave等。
Hive可以通过StarRocks/Doris等联邦查询数据库对接。
hbase和redis貌似不是SQL体系，估计比较难。
oracle是商用数据库，语法挺复杂，应该是可以安排对接的。

**Comment by wap1990-0903** [comment]
目前连接doris时可以通过的，就是希望能尽快对接下oracle

**Comment by dawsongzhao0523** [comment]
> 目前连接doris时可以通过的，就是希望能尽快对接下oracle

你们什么场景下，需要oracle的对接？目前开源社区，大部分产品对接Oracle动力都不足。毕竟都在国产化和去O

**Comment by Slach** [comment]
支持clickhouse会完美的事情
