### ISSUE TITLE
【问答对话】执行报错，无执行SQL生成

### ISSUE THREAD

**Issue by dawsongzhao0523** [tencentmusic/supersonic#1161]
## 现象
<img width="1183" alt="image" src="https://github.com/tencentmusic/supersonic/assets/133857587/2fd4c3c3-3bc5-45e6-a0a1-3506eac506f3">

### 语义模型建模SQL
通过SQL生成语义模型
```sql
select * from hive.dim.dim_employee
```
### 数据库
Starrocks

## 错误堆栈
<img width="1064" alt="image" src="https://github.com/tencentmusic/supersonic/assets/133857587/f89e12b5-cefe-4c0b-8c44-4a77bae54e0d">
<img width="999" alt="image" src="https://github.com/tencentmusic/supersonic/assets/133857587/10bd21ee-1ef1-45e1-8906-bfa3249ed7bd">
## 错误原因
目前不支持hive.dim.xxx 这类表名

**Comment by dawsongzhao0523** [comment]
数据集底层表字段，包含关键字，也会报错：
<img width="1025" alt="image" src="https://github.com/tencentmusic/supersonic/assets/133857587/f0959674-1d11-4d53-b7cd-ce675f50afde">

**Comment by jerryjzhang** [comment]
@jipeli 来看看SQL解析的问题
