### ISSUE TITLE
前一天还好好的，隔天重启后看似查找插件的时候报错(重启后却又没报错了)，以下是当时报错的地方和一些参数

### ISSUE THREAD

**Issue by baiying319** [tencentmusic/supersonic#1168]
<img width="1031" alt="image" src="https://github.com/tencentmusic/supersonic/assets/38554352/fedc31c8-a863-4c5f-af07-495cadcc1643">
![Uploading image.png…]()

private static Nature changeModel2DataSet(String nature, Long dataSetId) {
        try {
            String[] split = nature.split(DictWordType.NATURE_SPILT);
            if (split.length <= 1) {
                return null;
            }
           //这里把split[1]有原本的6替换成了5
            split[1] = String.valueOf(dataSetId);
            return com.hankcs.hanlp.corpus.tag.Nature.create(StringUtils.join(split, DictWordType.NATURE_SPILT));
        } catch (NumberFormatException e) {
            log.error("", e);
        }
        return null;
    }

StringUtils.join(split, DictWordType.NATURE_SPILT) 的结果是 : _5_10_metric
报错 :Index 287 out of bounds for length 287

**Comment by jerryjzhang** [comment]
@lexluo09 看看这个问题

**Comment by lexluo09** [comment]
嗯嗯，好的

**Comment by lexluo09** [comment]
这个问题是正常的，词典存储的是：modelId，此处功能是将modelId转换为dataSetId

**Comment by lexluo09** [comment]
报错 :Index 287 out of bounds for length 287 这个问题已进行修复

https://github.com/tencentmusic/supersonic/pull/1510
