### ISSUE TITLE
【问答对话】开启调试信息情况，支持“导出日志”

### ISSUE THREAD

**Issue by jerryjzhang** [tencentmusic/supersonic#1173]
### 需求说明

当助理开启调试模式情况下，每次问答可以查看到中间过程的日志，但是目前需要在界面上操作，切换不同的TAB，定位问题效率不高。考虑增加一个【导出日志】的功能，可以将涉及本次问答的日志导出。

导出日志命名：supersonic-debug-{{agentId}}-{{queryId}}.log

**Comment by williamhuanliu** [comment]
https://github.com/tencentmusic/supersonic/pull/1482
