### ISSUE TITLE
【问答对话】明细查询模式不能正常执行

### ISSUE THREAD

**Issue by dawsongzhao0523** [tencentmusic/supersonic#1180]
# 问题
问答： "姓名：xxx的详情数据"
语义SQL解析：
```sql
SELECT
  *
FROM
  员 工 基 础 信 息 数 据
WHERE
  姓 名 = 'xxx'
```
复合预期。
期望返回：
1、类似数据库标准查询模式，放回所有列。
2、如果按产品的设计逻辑，至少应该返回
```sql
select 所有tag的维度列和指标列 
FROM
  员 工 基 础 信 息 数 据
WHERE
  姓 名 = 'xxx'
```
但是，当前的物理SQL返回的是：
```sql
SELECT
  *
FROM
  (
    SELECT
      `emp_name`,
      1 AS `dimemployee_internal_cnt`
    FROM
      sda.dim_employee_base_info
  ) t_11
WHERE
  emp_name = 'xxx'
```
这种返回的结果与数据库正常使用习惯差异太大。建议修改。

# 问题定位：

com.tencent.supersonic.headless.server.utils.QueryReqConverter#convert(com.tencent.supersonic.headless.api.pojo.request.QuerySqlReq, com.tencent.supersonic.headless.api.pojo.response.SemanticSchemaResp)
<img width="1020" alt="image" src="https://github.com/tencentmusic/supersonic/assets/133857587/2981c4c5-7d14-4998-92ab-4453622b7fe8">
这个代码逻辑强制转换【明细查询模式】为【指标】类型的查询了。

**Comment by jerryjzhang** [comment]
明细查询下，"select *"最好替换成"select <为明细模式配置的字段>"

**Comment by lexluo09** [comment]
https://github.com/tencentmusic/supersonic/pull/1186
