### ISSUE TITLE
【Map映射】目前日期中的数字容易和已有纬度值冲突

### ISSUE THREAD

**Issue by lexluo09** [tencentmusic/supersonic#1182]
背景：比如"2024年xxxxxx"，中的0和已有的纬度值为0进行了重合；

<img width="1744" alt="image" src="https://github.com/tencentmusic/supersonic/assets/39718951/3443868e-be72-4013-ab0d-532105feea1a">

考虑：一个字的维度值（或数字）不做映射；

**Comment by lxwcodemonkey** [comment]
#1237 @baiying319 可以再试试~
