### ISSUE TITLE
[Enhancement] 【prompt管理】支持用户自定义prompt及增加prompt规则

### ISSUE THREAD

**Issue by dawsongzhao0523** [tencentmusic/supersonic#1247]
### Search before asking

- [X] I had searched in the [issues](https://github.com/tencentmusic/supersonic/issues?q=is%3Aissue) and found no similar issues.

## 问题：
有些场景，用户可以通过自己调整部分约束或者做自定义
## 方案：
1、制定Prompt模版
将现有的Prompt分为Role、Task、DDLInfo、Rules、Exemplars几部分；
2、Rules、Exemplars两个部分支持用户通过界面配置
## 实施
1、系统管理，增加Prompt管理功能（查看现在的Prompt、修改后的prompt、prompt测试等）、知识库管理功能

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by jerryjzhang** [comment]
赞同，可以在每个助理层面去设置自定义的prompt，需要先提炼一下内容构成，把可自定义的提炼出来

**Comment by jerryjzhang** [comment]
已经在#1348包含着部分特性。
