### ISSUE TITLE
[question] 修改supersonic-env.sh的配置为千问，报URL无效

### ISSUE THREAD

**Issue by integrityh** [tencentmusic/supersonic#1262]
### Describe your question

SuperSonic版本：0.9.2
`OPENAI_API_BASE=https://dashscope.aliyuncs.com/api/v1/apps/{我的app_id}/completion
OPENAI_API_KEY={我的api_key}
OPENAI_MODEL_NAME=Qwen-MAX`

报错信息：Exception was thrown on attempt 1 of 3
dev.ai4j.openai4j.OpenAiHttpException: {"request_id":"b5ae7167-a59d-9a06-9bca-917eb56c1a95","code":"InvalidURL","message":"Invalid URL provided in your request."}

上方的api_base和api_key使用curl请求是正常的。

请问还有哪些方面的原因导致URL无效呢。

application-local.yaml

server:
  port: 9080
  compression:
    enabled: true
    min-response-size: 1024
    mime-types: application/javascript,application/json,application/xml,text/html,text/xml,text/plain,text/css,image/*

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/supersonic?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true
    username: sonic
    password: sonic
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations=classpath:mappers/custom/*.xml,classpath*:/mappers/*.xml

authentication:
  enable: true
  exclude:
    path: /api/auth/user/register,/api/auth/user/login
  token:
    http:
      header:
        key: Authorization

logging:
  level:
    dev.langchain4j: DEBUG
    dev.ai4j.openai4j: DEBUG

s2:
  pyllm:
    url: http://127.0.0.1:9092

  parser:
    url: ${s2.pyllm.url}
    strategy: TWO_PASS_AUTO_COT_SELF_CONSISTENCY
    exemplar-recall:
      number: 10
    few-shot:
      number: 5
    self-consistency:
      number: 1
    multi-turn:
      enable: false

  corrector:
    additional:
      information: true

  functionCall:
    url: ${s2.pyllm.url}

  embedding:
    url: ${s2.pyllm.url}
    persistent:
      path: /tmp

  demo:
    names: S2VisitsDemo,S2ArtistDemo
    enableLLM: true

  langchain4j:
    chat-model:
      provider: open_ai
      openai:
        base-url: ${OPENAI_API_BASE:https://api.openai.com/v1}
        api-key: ${OPENAI_API_KEY:demo}
        model-name: ${OPENAI_MODEL_NAME:gpt-3.5-turbo}
        temperature: ${OPENAI_TEMPERATURE:0.0}
        timeout: ${OPENAI_TIMEOUT:PT60S}
    embedding-model:
      provider: in_process

**Comment by spider1998** [comment]
使用的base_url不对，官网有给说明：https://help.aliyun.com/zh/dashscope/developer-reference/compatibility-of-openai-with-dashscope
![image](https://github.com/user-attachments/assets/cf8cc4a0-8035-4408-8163-9af00736f437)
