### ISSUE TITLE
[Bug]  前端 sql-formatter ^2.3.3 升级到 sql-formatter ^15.3.2 导致 rollup 打包报错

### ISSUE THREAD

**Issue by HweiH** [tencentmusic/supersonic#1276]
### Search before asking

- [X] I had searched in the [issues](https://github.com/tencentmusic/supersonic/issues?q=is%3Aissue) and found no similar issues.

### Version

master 分支

### What's Wrong?

前端 sql-formatter ^2.3.3 升级到 sql-formatter ^15.3.2 导致 rollup 打包报错

### What You Expected?

前端回退到 sql-formatter ^2.3.3，但是要评估下

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by williamhuanliu** [comment]
将rollup-plugin-typescript2升级到0.36.0后问题已解决
<img width="473" alt="image" src="https://github.com/tencentmusic/supersonic/assets/137068196/914c74f8-f00e-478f-9e63-303439b1a471">
