### ISSUE TITLE
[question] 时间筛选是必须的吗

### ISSUE THREAD

**Issue by oleolema** [tencentmusic/supersonic#1304]
### Describe your question

这里我想查询的数据没有时间范围，但SQL中还是生成了时间的过滤条件，即使数据集里没有时间字段
<img width="1217" alt="image" src="https://github.com/tencentmusic/supersonic/assets/34965368/63c6bc7d-139a-48e3-8184-89cc1ac75d5d">

<img width="1223" alt="image" src="https://github.com/tencentmusic/supersonic/assets/34965368/23e4b0c0-6af4-4bf6-95d4-f33127a8665d">

**Comment by dao24dao** [comment]
哈喽，请问这个问题解决了吗？

**Comment by oleolema** [comment]
> 哈喽，请问这个问题解决了吗？

还没有解决，等待大佬来解决

**Comment by dawsongzhao0523** [comment]
<img width="1789" alt="image" src="https://github.com/tencentmusic/supersonic/assets/133857587/1f6cfc5d-c52b-443a-96b6-e267d5d09778">
<img width="973" alt="image" src="https://github.com/tencentmusic/supersonic/assets/133857587/e525b4a9-6515-43fc-b95e-46f9d26d523c">
语义建模-数据集-查询设置-查询时间 都设置为 -1
