### ISSUE TITLE
[Feature] 【语义建模】支持智能建模，降低冷启动成本

### ISSUE THREAD

**Issue by jerryjzhang** [tencentmusic/supersonic#1319]
### Search before asking

- [X] I had searched in the [issues](https://github.com/tencentmusic/supersonic/issues?q=is%3Aissue) and found no similar issues.

### 背景

当前要开启问答对话，需要先构建好语义模型，在其中定义好指标、维度等模型实体。但是，对于想快速体验问答效果的用户来说，这个冷启动成本相对较高。

设计智能建模的功能，用户只需要指定数据库表，由系统借助大模型的能力，自动解析元数据字段，并创建出指标、维度。智能建模结束后，可由用户来做复核或者补充，从而降低冷启动的建模成本。

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by dawsongzhao0523** [comment]
这个特性太棒了，我这边也在探索这一块。通过大模型推测表的用途，字段的用途，同时，采样每个字段的值（如果是维度字段，数量在10以内的，例如，男女、是否这类，直接填写到备注。如果是数据量大的，例如姓名、工厂等实体名称，就采样5-10个），自动生成描述信息。以及敏感层级。

**Comment by lxwcodemonkey** [comment]
@ #1833

**Comment by lxwcodemonkey** [comment]
#1848
