### ISSUE TITLE
[Bug] dockerfile 少了入参，导致生产环境生效的是local.yml

### ISSUE THREAD

**Issue by jackiezzq** [tencentmusic/supersonic#1330]
### Search before asking

- [X] I had searched in the [issues](https://github.com/tencentmusic/supersonic/issues?q=is%3Aissue) and found no similar issues.

### Version

0.9.4

### What's Wrong?

![image](https://github.com/tencentmusic/supersonic/assets/18511799/9f72accb-cd8f-427b-9fd4-40d59baeb088)
![image](https://github.com/tencentmusic/supersonic/assets/18511799/c87d96a4-3d91-44a9-bafd-50ca5c5e0550)
这里不存在入参3，导致生效的配置一直是local
 

### What You Expected?

docker 使用prd配置

### How to Reproduce?

dockerfile 增加service入参

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by lexluo09** [comment]
确实，存在这个问题，谢谢你的建议

**Comment by lexluo09** [comment]
https://github.com/tencentmusic/supersonic/pull/1332

**Comment by lexluo09** [comment]
已修复
