### ISSUE TITLE
问答界面，文案错误

### ISSUE THREAD

**Issue by ccckdi** [tencentmusic/supersonic#135]
![image](https://github.com/tencentmusic/supersonic/assets/56465277/f1f5a19a-2c1c-428f-9b6d-ad3a86b009aa)

**Comment by williamhuanliu** [comment]
这个是比较老的版本的界面了，是否可以用新版本的看看

**Comment by jerryjzhang** [comment]
@ccckdi 你好，请问还有疑问吗
