### ISSUE TITLE
[Enhancement] 【问答对话】所有指标支持跳转指标市场

### ISSUE THREAD

**Issue by jerryjzhang** [tencentmusic/supersonic#1365]
### Search before asking

- [X] I had searched in the [issues](https://github.com/tencentmusic/supersonic/issues?q=is%3Aissue) and found no similar issues.

### 背景

当前问答对话在筛选条件、相似推荐等区域都会显示指标，可以支持跳转指标市场，可让用户对指标有更多的认识

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by lincanfeng** [comment]
请问如何才能让模型推荐指标和维度呢，期待您的回复~
