### ISSUE TITLE
[Enhancement] 升级底层 Spring Boot 版本至 2.7.2

### ISSUE THREAD

**Issue by HweiH** [tencentmusic/supersonic#1367]
### Search before asking

- [X] I had searched in the [issues](https://github.com/tencentmusic/supersonic/issues?q=is%3Aissue) and found no similar issues.

### Description

升级底层 Spring Boot 版本至 2.7.2

### Solution

升级底层 Spring Boot 版本至 2.7.2

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by jerryjzhang** [comment]
可以帮忙提交PR吗

**Comment by HweiH** [comment]
已提价PR哈
