### ISSUE TITLE
http://117.72.46.148:9080/chat?agentId=1权限问题

### ISSUE THREAD

**Issue by younggggger** [tencentmusic/supersonic#1369]
### Describe your question

您没有模型[用户部门]权限，请联系管理员[admin, alice]开通            请问怎么开通 权限

**Comment by dawsongzhao0523** [comment]
<img width="926" alt="image" src="https://github.com/tencentmusic/supersonic/assets/133857587/4f6bd519-c81b-4394-846a-7b526459d039">
<img width="1149" alt="image" src="https://github.com/tencentmusic/supersonic/assets/133857587/251bef2e-efad-4f46-b741-f90a982d4b38">
