### ISSUE TITLE
[Bug] 在云服务上 基于 docker-compose 容器部署 界面无法访问

### ISSUE THREAD

**Issue by chuyangkongling** [tencentmusic/supersonic#1378]
### Search before asking

- [X] I had searched in the [issues](https://github.com/tencentmusic/supersonic/issues?q=is%3Aissue) and found no similar issues.

### Version

v0.9.4

### What's Wrong?

无法访问主页面，防火墙端口已开放，docker 镜像正常启动
![Uploading docker-ps.png…](docker 容器)

![Uploading docker-port.png…](docker 端口)

![Uploading docker-firewall.png…](云服务器防火墙配置)

![Uploading docker-mysql.png…](mysql 启动日志)

### What You Expected?

I don't know where the problem, can help fix it

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by chuyangkongling** [comment]
![docker-ps](https://github.com/tencentmusic/supersonic/assets/16522527/8b4831f1-707f-4efa-9d54-83eec11cad68)

![docker-mysql](https://github.com/tencentmusic/supersonic/assets/16522527/a9211640-8458-4587-91e5-684702e96377)

![docker-port](https://github.com/tencentmusic/supersonic/assets/16522527/4a7d734f-b0ec-48d6-b104-55be35cab64d)

![docker-firewall](https://github.com/tencentmusic/supersonic/assets/16522527/fe02859f-05c1-4363-aca1-dc1da734542e)

**Comment by chuyangkongling** [comment]
图片附件
![docker-ps](https://github.com/tencentmusic/supersonic/assets/16522527/8b8c026c-f419-4dcd-acc8-3b89557616ad)
![docker-mysql](https://github.com/tencentmusic/supersonic/assets/16522527/42243d01-364e-4cf2-ad3d-2bc96043c944)
![docker-port](https://github.com/tencentmusic/supersonic/assets/16522527/07dee98f-2caa-4e54-be44-7e9f01f52f88)
![docker-firewall](https://github.com/tencentmusic/supersonic/assets/16522527/5dd5b562-1d24-42d1-baef-fb98fde78fdf)

**Comment by lexluo09** [comment]
您好，我在腾讯云服务器上跑了是正常可以访问

**Comment by lexluo09** [comment]
经过定位是该腾讯云服务器内存2G，导致服务无法正常启动
