### ISSUE TITLE
[Enhancement] 增加记忆助手开关

### ISSUE THREAD

**Issue by dawsongzhao0523** [tencentmusic/supersonic#1385]
### Search before asking

- [X] I had searched in the [issues](https://github.com/tencentmusic/supersonic/issues?q=is%3Aissue) and found no similar issues.

### Description

![image](https://github.com/tencentmusic/supersonic/assets/133857587/5ab7a9f6-cd7b-43dc-8493-fca1b8d68715)
记忆管理功能，评估代码准确性，比较耗tocken，建议增加配置开关。

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by jerryjzhang** [comment]
没问题，在助理中增加一个开关，“开启大模型记忆评估”
