### ISSUE TITLE
[question] 我的数据库只有只读权限，但是貌似每次他都必须要initial一些表。请问对于只读的数据库，我该如何修改代码配置？

### ISSUE THREAD

**Issue by BrianXiao1** [tencentmusic/supersonic#1389]
### Describe your question

我的数据库只有只读权限，但是貌似每次他都必须要initial一些表。请问对于只读的数据库，我该如何修改代码配置？

**Comment by jerryjzhang** [comment]
数据库区分两个场景，一个是存储supersonic自身的数据，这个肯定需要有写权限；二个是用于查询数据，这个读权限就够了。第一个场景，可以自己搭建一个数据库就行，或者采用docker部署，系统默认采用mysql来存储数据。
