### ISSUE TITLE
[Enhancement] 增加个人中心操作界面

### ISSUE THREAD

**Issue by flyskyopen** [tencentmusic/supersonic#1399]
### Search before asking

- [X] I had searched in the [issues](https://github.com/tencentmusic/supersonic/issues?q=is%3Aissue) and found no similar issues.

### Description

[Enhancement] 增加个人中心操作界面，用户进来第一眼可看到查询多少会话 配置多少指标维度，累计访问次数 时间  收藏下载等信息

### Solution

[Enhancement] 增加个人中心操作界面，用户进来第一眼可看到查询多少会话 配置多少指标维度，累计访问次数 时间  收藏下载等信息

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by jerryjzhang** [comment]
这个建议不错，是否愿意参与提交PR呢
