### ISSUE TITLE
[Enhancement] 【问答对话】优化图表依据查询结果的自适应能力

### ISSUE THREAD

**Issue by jerryjzhang** [tencentmusic/supersonic#1402]
### Search before asking

- [X] I had searched in the [issues](https://github.com/tencentmusic/supersonic/issues?q=is%3Aissue) and found no similar issues.

### Description

1. 如果是多个指标，就默认用表格来展示
<img width="1511" alt="image" src="https://github.com/tencentmusic/supersonic/assets/3949293/0b250d6b-06cd-4fc1-b6c4-36ead550d791">

2. 如果不是展示趋势的折线图，比如柱状图或者表格，可以根据数据列的数量来自适应宽度，不用默认全屏宽度。
<img width="1531" alt="image" src="https://github.com/tencentmusic/supersonic/assets/3949293/697ae683-86da-40a8-a64d-d989d8de58fa">

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by 15074852943** [comment]
为什么第一次查询返回的是表格形式，不能切换成其他图表呢？
