### ISSUE TITLE
[Enhancement] 【术语管理】增加查询和批量删除操作

### ISSUE THREAD

**Issue by shyShang** [tencentmusic/supersonic#1408]
### Search before asking

- [X] I had searched in the [issues](https://github.com/tencentmusic/supersonic/issues?q=is%3Aissue) and found no similar issues.

### Description

当自定义的术语特别多时，无法快速找到已有术语，且逐一删除效率低下

### Solution

- 希望增加查询功能快速定位进行编辑
- 希望增加批量删除功能

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by dawsongzhao0523** [comment]
这个我们内部已经实现
![image](https://github.com/user-attachments/assets/fb6ecddd-2502-43a0-8273-05e4c71373ab)
![image](https://github.com/user-attachments/assets/2b5812a7-f253-46aa-9d6d-ddb27d8c2ef0)
代码提交到#1445 PR了

**Comment by sevenliu1896** [comment]
feat: #1735
