### ISSUE TITLE
字典数据如何生产？

### ISSUE THREAD

**Issue by ddouble1987** [tencentmusic/supersonic#1414]
### Describe your question

0.9.4版本是否支持语义字典的自动生产或者批量导入？

**Comment by jerryjzhang** [comment]
批量导入暂时还不支持，是系统自动抽取生成的

**Comment by ShawshankLin** [comment]
> 批量导入暂时还不支持，是系统自动抽取生成的

是定时抽取吗？还是要去后台触发导入才可以？抽取的方式是如何呢，直接从数仓select distinct字段写进去？
