### ISSUE TITLE
启动时候找不到oonxruntime.dll文件，而且每次启动都会在windows下生成一个新的目录onnxruntime-java4286939494773097576导致出来如下问题

### ISSUE THREAD

**Issue by wanggaoxing111** [tencentmusic/supersonic#1415]
### Describe your question

![a99fe0b6693b59c04ba0c6a0dde1159](https://github.com/user-attachments/assets/37f3d5d1-0906-4ebe-b11b-a636cffd9e55)

**Comment by lexluo09** [comment]
感谢您的反馈，我们看看

**Comment by Drjuror** [comment]
@lexluo09 大佬，麻烦看下，我也出现同样的问题

**Comment by lexluo09** [comment]
https://blog.csdn.net/bailanren/article/details/136656636

**Comment by lexluo09** [comment]
本地没有对应的包，下载对应的包试试，或者使用docker
