### ISSUE TITLE
[question] How to config LLM to local Ollama service?

### ISSUE THREAD

**Issue by RTException** [tencentmusic/supersonic#1416]
### Describe your question

After configuring the address of ollama on the page, I clicked the "Large Model Connection Test" button, and the page displayed that the model connection failed, but I ran qwen:7b in ollama on my local machine.
<img width="1508" alt="image" src="https://github.com/user-attachments/assets/220446c4-012f-4eb5-98c4-17a21ae1913c">
![image](https://github.com/user-attachments/assets/d3a9b36e-450f-4aa5-bfcc-d78ac7ef30b8)

### What have you tried to resolve your question

I have consulted the "Configure LLM" section on [Docs](https://supersonicbi.github.io/docs), in the screenshot, only the Interface Protocol field is filled with OLLAMA, the Model Name and Base URL are both empty.

**Comment by lexluo09** [comment]
感谢您的反馈，我们看看

**Comment by RTException** [comment]
我发现了，`model name`必须输入`ollama`启动命令一致的模型名称。当启动模型使用`ollama run llama3`时，`model name`输入`llama3`；当启动模型使用`ollama run llama3:8b`时，`model name`输入`llama3:8b`。
