### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by zhjiguang** [tencentmusic/supersonic#1422]
### Search before asking

- [X] I had searched in the [issues](https://github.com/tencentmusic/supersonic/issues?q=is%3Aissue) and found no similar issues.

### Version

运行java onnxruntime.dll can't find dependent libraries

### What's Wrong?

运行java onnxruntime.dll can't find dependent libraries

### What You Expected?

期望解决

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by jerryjzhang** [comment]
建议还是走docker部署方式，这个看起来是本地系统lib有缺失
