### ISSUE TITLE
[question] 为什么源码部署的情况下，在ubuntu环境运行shell脚本没有反应，等了很久还是保持在空白log的状态？

### ISSUE THREAD

**Issue by dj-jack001** [tencentmusic/supersonic#1425]
### Describe your question

为什么源码部署的情况下，在ubuntu环境运行shell脚本没有反应，等了很久还是保持在空白log的状态？

### What have you tried to resolve your question

按文档部署步骤执行

### Your environment

Ubuntu22.04，jdk1.8环境

### Screenshots or Logs

![image](https://github.com/user-attachments/assets/2c5e7424-39db-40c8-a39e-5420fc414d26)

![image](https://github.com/user-attachments/assets/1ec48ca3-6e8a-44e1-9256-9dc53840db4b)

**Comment by jerryjzhang** [comment]
没有显式报错的，不太好猜测是什么原因，本地环境有太多可能性了。建议可以直接修改下supersonic-build.sh，在一些步骤加echo来看下卡在哪个命令了
