### ISSUE TITLE
[question] Is it possible to run SuperSonic in English (is i18n support available) ? 

### ISSUE THREAD

**Issue by sumittongya** [tencentmusic/supersonic#1440]
### Describe your question

[question] Is it possible to run SuperSonic in English (is i18n support available) ?

**Comment by jerryjzhang** [comment]
yes, i18n should be working fine. Also, we are planning to support English on the UI.

**Comment by sumittongya** [comment]
English UI. is this done ? if yes, please let me know the version on which i can try.  I am really eager to try this out. thanks
