### ISSUE TITLE
库表名大小写敏感导致库表名找不到问题

### ISSUE THREAD

**Issue by yangjs2023** [tencentmusic/supersonic#1452]
### Describe your question

Doris数据库库表名大小写敏感，当数据库中库表名指定为大写时，在指标探索时库名被转成小写，导致在数据库找不到对应的库表名 

### Provide any additional context or information

Doris数据库库表名大小写敏感，在指标探索的时库名被转成小写，导致在数据库找不到 对应的库名

**Comment by jerryjzhang** [comment]
@daikon12 看看是不是自动做了转小写
