### ISSUE TITLE
where条件有in时，维度值的中文不会被替换成设置的技术名称

### ISSUE THREAD

**Issue by mxli441** [tencentmusic/supersonic#1459]
### Search before asking

- [X] I had searched in the [issues](https://github.com/tencentmusic/supersonic/issues?q=is%3Aissue) and found no similar issues.

### Version

supersonic 0.9.2

### What's Wrong?

大模型生成如下SQL：
SELECT
  业 务 类 型,
  占 比
FROM
  当 日 指 标
WHERE
 业 务 类 型 IN ('业务1', '业务2')
  AND 数 据 日 期 = '2024-07-26'

![image](https://github.com/user-attachments/assets/9571a4a8-504c-48d2-a62a-4be736b29431)

![1721963907353](https://github.com/user-attachments/assets/9c4180c9-eb3c-46fe-941e-8e17a95dc352)

在SqlReplaceHelper第137行
        for (PlainSelect plainSelect : plainSelects) {
            Expression where = plainSelect.getWhere();
            FieldlValueReplaceVisitor visitor = new FieldlValueReplaceVisitor(exactReplace, filedNameToValueMap);
            if (Objects.nonNull(where)) {
                where.accept(visitor);
            }
        }
        return selectStatement.toString();
执行完成后，原代码中的维度值未被替换

### What You Expected?

希望生成正确的SQL:
SELECT
  业 务 类 型,
  占 比
FROM
  当 日 指 标
WHERE
 业 务 类 型 IN ('48', '73')
  AND 数 据 日 期 = '2024-07-26'

### Anything Else?

NO

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by lexluo09** [comment]
感谢您的反馈
