### ISSUE TITLE
[Bug] 切换解析的时候会有一个请求404

### ISSUE THREAD

**Issue by minpod** [tencentmusic/supersonic#1467]
### Search before asking

- [X] I had searched in the [issues](https://github.com/tencentmusic/supersonic/issues?q=is%3Aissue) and found no similar issues.

### Version

此时最新版本

### What's Wrong?

![image](https://github.com/user-attachments/assets/e0e83278-1a8c-46db-96ed-1af1eaa4296e)

### What You Expected?

fix

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by williamhliu** [comment]
最新master分支代码已解决这个问题
