### ISSUE TITLE
[Bug] 不管周期是周、月、年，endDate应该都是昨天，这里的enddate看起来是提前了一个对应周期

### ISSUE THREAD

**Issue by whyuds** [tencentmusic/supersonic#1471]
### Search before asking

- [X] I had searched in the [issues](https://github.com/tencentmusic/supersonic/issues?q=is%3Aissue) and found no similar issues.

### Version

f0bdb14818582c143eeaefa590276f91e4aafa58
[improvement][headless-fe] Added password parsing to the generation rules of system settings. (#1451) tristanliu* 2024/7/25 11:35

### What's Wrong?

比如数据集查询设置设置为最近30天正常，但如果为最近1个月，查询时不出来数据

![image](https://github.com/user-attachments/assets/434b01d2-4f0a-4a63-8958-51c78eb88d3a)
数据集：浏览日期 浏览量
Query: 最近3天浏览量
![image](https://github.com/user-attachments/assets/e39f180e-d41a-4a67-b9de-0a0f07f899f8)

### What You Expected?

即使最近1个月、1年，截止日期应该跟最近1天是一致的

### How to Reproduce?

![image](https://github.com/user-attachments/assets/434b01d2-4f0a-4a63-8958-51c78eb88d3a)

### Anything Else?

None

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by jerryjzhang** [comment]
我们来复现一些看看，另外确认下是否会提交PR呢？

**Comment by jerryjzhang** [comment]
已经复现并修复

**Comment by whyuds** [comment]
> 已经复现并修复
点赞，辛苦
