### ISSUE TITLE
[Enhancement] performParsing性能优化，目前平均1-2s左右的性能损耗

### ISSUE THREAD

**Issue by dawsongzhao0523** [tencentmusic/supersonic#1472]
### Search before asking

- [X] I had searched in the [issues](https://github.com/tencentmusic/supersonic/issues?q=is%3Aissue) and found no similar issues.

### Description

![image](https://github.com/user-attachments/assets/7c994f59-f4f9-4d46-9a63-2b29446315c3)

debug日志发现大量的数据库查询：
<img width="1214" alt="image" src="https://github.com/user-attachments/assets/d8d9a80d-dff2-4a48-8041-d519df8cfaa2">

[执行日志debug.log](https://github.com/user-attachments/files/16408878/debug.log)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by jerryjzhang** [comment]
收到，我们来详细看看

**Comment by jerryjzhang** [comment]
已经做了一些改进，降低了数据库查询的开销：
1、减少对s2_tag, s2_domain表的查询次数；
2、默认打开`s2.schema.cache.enable`开关；
当然，还存在减少数据库查询的空间，后续会持续优化
