### ISSUE TITLE
[Feature] 什么时候能支持odps

### ISSUE THREAD

**Issue by zhaolianghz** [tencentmusic/supersonic#1474]
### Search before asking

- [X] I had searched in the [issues](https://github.com/tencentmusic/supersonic/issues?q=is%3Aissue) and found no similar issues.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by jerryjzhang** [comment]
我们团队没有用过ODPS，它是有提供jdbc驱动JAR文件吗？

**Comment by jerryjzhang** [comment]
已经规划在0.9.6版本取消对数据库类型的限制，理论上只要将数据库的jdbc驱动文件放入supersonic的lib目录，即可正常对接，可以参考 https://github.com/tencentmusic/supersonic/issues/1490
