### ISSUE TITLE
[Bug] 大模型解析正确，最终解析的SQL差距比较大

### ISSUE THREAD

**Issue by 343635120** [tencentmusic/supersonic#1485]
### Search before asking

- [X] I had searched in the [issues](https://github.com/tencentmusic/supersonic/issues?q=is%3Aissue) and found no similar issues.

### Version

最后一个

### What's Wrong?

![1](https://github.com/user-attachments/assets/8ca5400e-13aa-4864-85db-481283eeff60)
![image](https://github.com/user-attachments/assets/96ba04f0-0954-480c-9fdd-5c52687d31e7)

最终执行的SQL为：
with
  t_4 as (
    SELECT
      sys_imp_date,
      yylr
    FROM
      (
        SELECT
          sys_imp_date,
          tbacwsj - nd - date_yylr AS yylr
        FROM
          (
            SELECT
              SUM(tbacwsj - nd - date_yylr) AS tbaCwsj - nd - date_yylr,
              sys_imp_date,
              sjrq
            FROM
              (
                SELECT
                  yylr AS tbaCwsj - nd - date_yylr,
                  sjrq AS sys_imp_date,
                  sjrq AS sjrq
                FROM
                  (
                    SELECT
                      to_date (concat (nd, '0101'), 'yyyymmdd') AS sjrq,
                      a.*
                    FROM
                      tba_cwsj AS a
                  ) AS tbaCwsj - nd - date
              ) AS src00_tbaCwsj - nd - date_1b17
            GROUP BY
              sys_imp_date,
              sjrq
          ) AS tbaCwsj - nd - date_0
      ) AS tbaCwsj - nd - date_1
  )
SELECT
  SUM(yylr)
FROM
  t_4
WHERE
  sys_imp_date >= '2023-01-01'
  AND sys_imp_date <= '2023-12-31'
limit
  1000

1：指标少了
2：中间字段别名（  yylr AS tbaCwsj - nd - date_yylr）、表别名（ AS tbaCwsj - nd - date）中含有空格和减号等非法字段

正确的应该是：
with t4 as (
  SELECT
                      to_date (concat (nd, '0101'), 'yyyymmdd') AS sjrq,
                      a.*
                    FROM
                      tba_cwsj AS a
)select sum(yylr),sum(yysr)
from t_4 WHERE
  sjrq>= '2023-01-01'
  AND sjrq<= '2023-12-31'
![2](https://github.com/user-attachments/assets/75f52c14-549e-4d1d-b397-60a155086615)

### What You Expected?

能给出可执行的SQL

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by jipeli** [comment]
"tbaCwsj - nd - date" is taken from the bizName of the model , modify it to [_a-zA-Z0-9]+  and try again
