### ISSUE TITLE
[Bug] 导入维度值错误

### ISSUE THREAD

**Issue by tom1978** [tencentmusic/supersonic#1486]
### Search before asking

- [X] I had searched in the [issues](https://github.com/tencentmusic/supersonic/issues?q=is%3Aissue) and found no similar issues.

### Version

0.94

### What's Wrong?

导入维度值发生错误：
![33b0c083bb3b4d385bb660b00e9ab0b](https://github.com/user-attachments/assets/4e0a33d1-f5f2-4ec2-bee8-621accced399)
![4a16ae1be5c32140c044a658bf7c3fe](https://github.com/user-attachments/assets/11c42790-3250-45e3-a28d-a910b56953f3)
![f8f2e4dcb8837b374685a1e14134bf7](https://github.com/user-attachments/assets/a35edfcb-48a5-4633-b990-e60a0ab48fe8)

### What You Expected?

修正

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by daikon12** [comment]
the problem is caused by system format settings, relevant corrections were made：
https://github.com/tencentmusic/supersonic/pull/1497/files

**Comment by daikon12** [comment]
the problem is caused by system format settings, relevant corrections were made：
https://github.com/tencentmusic/supersonic/pull/1497/files
thanks for your feedback。
