### ISSUE TITLE
[Enhancement] OnePassSCSqlGenStrategy 类中生成的sqloutput 可能带有``` sql ```  导致报错，查不到数据集中的表

### ISSUE THREAD

**Issue by ylhh353** [tencentmusic/supersonic#1498]
### Search before asking

- [X] I had searched in the [issues](https://github.com/tencentmusic/supersonic/issues?q=is%3Aissue) and found no similar issues.

### Description

OnePassSCSqlGenStrategy 类中生成的sqloutput 可能带有``` sql ```  导致报错，查不到数据集中的表

### Solution

                    String sqlOutput = StringUtils.normalizeSpace(response.content().text());
                    // replace ```
                    String sqlOutputFormat = sqlOutput.replaceAll("(?s)```sql\\s*(.*?)\\s*```", "$1").trim();

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by jerryjzhang** [comment]
已经合并，感谢提交贡献
