### ISSUE TITLE
[Bug]【规则语义解析】表达“日期区间”的时间表达，结束日期解析错误

### ISSUE THREAD

**Issue by luguoqing** [tencentmusic/supersonic#1501]
### Search before asking

- [X] I had searched in the [issues](https://github.com/tencentmusic/supersonic/issues?q=is%3Aissue) and found no similar issues.

### Version

V0.9.4、最新代码

### What's Wrong?

表达“日期区间”的时间表达，开始日期解析正确，结束日期错误。

**示例**
1. 查询“去年”，开始日期为 2023-01-01，结束日期为 2023-01-01（期望：2023-12-31）
2. 查询“今年8月”，开始日期为 2024-08-01，结束日期为 2024-08-01（期望：2024-08-31）
3. 查询“2024年1月到3月”，开始日期为 2024-01-01，结束日期为 2024-03-01（期望：2023-03-31）
![image](https://github.com/user-attachments/assets/1dd5abeb-e4d2-409e-9c19-0d6e40d3c4af)

### What You Expected?

结束日期解析为 BUG 中期望日期

### Anything Else?

内部基于 xk-time 时间自然语言分析工具类实现。初步判断，其原生就不支持。

1. “今年8月”，xk-time 只会认定为日期，不认定为日期区间。即开始日期解析为 2024-08-01，结束日期未解析到，后置设定为开始日期
2. “2024年1月到3月”，xk-time 识别到 2 个日期（2024年1月、2024年3月），但2024年3月识别为2024-03-01

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by jerryjzhang** [comment]
基于规则的解析在日期表达上确实是不灵活的，没法做到LLM解析的程度，不算是BUG。当前规则解析仅推荐用于做DEMO和测试的场景
