### ISSUE TITLE
[Bug] 配置了数据集查询时间为-1，LLM生成没有时间限制但物理sql增加了时间限制

### ISSUE THREAD

**Issue by whyuds** [tencentmusic/supersonic#1508]
### Search before asking

- [X] I had searched in the [issues](https://github.com/tencentmusic/supersonic/issues?q=is%3Aissue) and found no similar issues.

### Version

ad83ea32fa1b7ad6726c770d53280f8401c4d845

### What's Wrong?

生成的LLMsql正常——SELECT 作品标题, 作品类型 FROM 杂志社数据 GROUP BY 作品标题, 作品类型 HAVING SUM(浏览量) >= 1000;

转物理sql时增加了时间过滤：
![image](https://github.com/user-attachments/assets/271d19ae-4af4-43b1-b291-a7f33a8733ef)

PS：已经配置数据集查询时间为-1

### What You Expected?

不希望出现时间过滤

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by jerryjzhang** [comment]
等你的PR，谢谢:)
