### ISSUE TITLE
[Bug] LLM解析的SQL是对的，修正后的SQL会增加额外理解导致错误

### ISSUE THREAD

**Issue by longlimin** [tencentmusic/supersonic#1525]
### Search before asking

- [X] I had searched in the [issues](https://github.com/tencentmusic/supersonic/issues?q=is%3Aissue) and found no similar issues.

### Version

输入的问题查询：2021年6月以后发布的李雨纯的播放量大于20万的歌曲有哪些

LLM解析的SQL是对的，
![image](https://github.com/user-attachments/assets/2286fc80-aca3-477e-9adc-48f6c0ac726a)

修正后就错误了：
![image](https://github.com/user-attachments/assets/299907f9-ff54-4066-841b-ea300d8174a2)

### What's Wrong?

修正后语义不符合预期

### What You Expected?

修正后把需要查询的的歌曲名去掉了，而歌手名本身就在查询内容中

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by lexluo09** [comment]
“发布日期”字段是不是没在数据集中配置

**Comment by longlimin** [comment]
您说得对， 发布日期，歌曲名称都要配置对， 看了TimeCorrector，SchemaCorrector等都做了强匹配性。 感谢您的回复
