### ISSUE TITLE
使用SQL脚本构建模型时的动态参数怎么使用？

### ISSUE THREAD

**Issue by GaoLe996** [tencentmusic/supersonic#1537]
### Describe your question

使用SQL脚本构建模型时的动态参数怎么使用？
![image](https://github.com/user-attachments/assets/af1bf00c-252e-4bbd-9ec6-3fda0c39f624)

### Your environment

MacOS 14

**Comment by lxwcodemonkey** [comment]
![image](https://github.com/user-attachments/assets/b6d268c1-5b12-4552-b1f9-16c8f04a5d4b)
可以参考下这里

**Comment by GaoLe996** [comment]
如果不能作用在只能问答上，那么数据就不能做分表了吧，那大量数据不分库分表，怎么提高响应速度呢？还请指点一二，万分感谢~~~

**Comment by lxwcodemonkey** [comment]
分库分表我理解是根据你的业务场景来的，规则可能是多种多样，即便能作用到问答，大模型也很难基于变量来根据你的规则实现分库分表路由的效果，或许对于这样大量数据需要进行分析的情况，使用Doris，ClickHouse这样的OLAP数据库呢

**Comment by GaoLe996** [comment]
万分感谢~~~
