### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by tom1978** [tencentmusic/supersonic#1540]
### Search before asking

- [X] I had searched in the [issues](https://github.com/tencentmusic/supersonic/issues?q=is%3Aissue) and found no similar issues.

### Version

0.9.6-SNAPSHOT

### What's Wrong?

当数据库对sql语句大小写敏感时，因为程序默认会把表名变为小写，所以导致查询出错
![Uploading 34e4f3b0ace4b4ea3edc11599f38c30.png…]()

### What You Expected?

能支持数据库sql语句对大小写敏感

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by jerryjzhang** [comment]
你好，这个跟 #1452 重复了
