### ISSUE TITLE
[Enhancement] 【语义建模】支持模型间非主键的关联

### ISSUE THREAD

**Issue by jerryjzhang** [tencentmusic/supersonic#1541]
### Search before asking

- [X] I had searched in the [issues](https://github.com/tencentmusic/supersonic/issues?q=is%3Aissue) and found no similar issues.

### Description

当前，系统假定两个语义模型间的关联字段，在两边都必须是主键，但在关系模型中是主键和外键之间关联。

### Solution

对语义模型的维度增加DimensionType.foreign_key，必须关联到另一个模型的DimensionType.primary_key

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by lxwcodemonkey** [comment]
#1857
