### ISSUE TITLE
[Feature] 【语义查询】查询结果数据量级limit自定义

### ISSUE THREAD

**Issue by 635160051** [tencentmusic/supersonic#1557]
### Search before asking

- [X] I had searched in the [issues](https://github.com/tencentmusic/supersonic/issues?q=is%3Aissue) and found no similar issues.

### Description

在查询完成数据后，默认limit 365，如数据量级较大有下钻维度的时候、以及查询日期较长，就会无法获取数据

### Use case

查询pvuv等情况下，下钻层级部门或者人员，limit 365完全不够用；日期较长查询历史数据汇总，无法满足

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by daikon12** [comment]
for or details on the optimization logic, see  https://github.com/tencentmusic/supersonic/pull/1688

**Comment by daikon12** [comment]
for details on the optimization logic, see https://github.com/tencentmusic/supersonic/pull/1688
