### ISSUE TITLE
[Enhancement] 用户点赞的结果可以加到few-shot里

### ISSUE THREAD

**Issue by whyuds** [tencentmusic/supersonic#1563]
### Search before asking

- [X] I had searched in the [issues](https://github.com/tencentmusic/supersonic/issues?q=is%3Aissue) and found no similar issues.

### Description

目前只有记忆管理里通过管理员或者大模型进行评判。大模型评判效果较差，管理员评判单点人力成本较高。
建议增加用户点赞的问答结果也加入freeshot中，错误、随意的评判可能影响其他人的结果，可以考虑：
1. 增加审核流程
2. 增加用户个人freeshot空间
3. 提高录入的交互摩擦

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by jerryjzhang** [comment]
关于记忆的审核和人工维护都已经在近期版本实现
