### ISSUE TITLE
[Enhancement] 【记忆管理】体验优化汇总

### ISSUE THREAD

**Issue by whyuds** [tencentmusic/supersonic#1564]
### Search before asking

- [X] I had searched in the [issues](https://github.com/tencentmusic/supersonic/issues?q=is%3Aissue) and found no similar issues.

### Description

![image](https://github.com/user-attachments/assets/91b1d4f5-463e-4432-8a13-13c7d6c59a3d)

1. 目前默认是按时间正序，倒序更符合用户交互
2. 增加点击title排序
3. [Bug]点击查询后，页脚的页数、条数不更新
4. 增加更新时间、创建时间列
5. 支持批量删除历史冗余问答结果

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by jerryjzhang** [comment]
很好的建议，会安排开发

**Comment by lxwcodemonkey** [comment]
#1741
