### ISSUE TITLE
[Enhancement] 【问答对话】Add question asking time display

### ISSUE THREAD

**Issue by jdzhang1221** [tencentmusic/supersonic#1573]
### Search before asking

- [X] I had searched in the [issues](https://github.com/tencentmusic/supersonic/issues?q=is%3Aissue) and found no similar issues.

### Description

Display the chat time of the Q&A conversation record，Similar to Feishu chat history
![82aa3e73-d028-4c02-b374-9b6a57dc43db](https://github.com/user-attachments/assets/a46fc23f-d2cb-405d-90d9-04513267c61a)

​​

### Solution

Display the time of the question and answer when the mouse hovers

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by williamhuanliu** [comment]
https://github.com/tencentmusic/supersonic/pull/1667
