### ISSUE TITLE
[question] Using llama3.1 to test the answer is wrong

### ISSUE THREAD

**Issue by jdzhang1221** [tencentmusic/supersonic#1574]
### Describe your question

Using llama3.1 to test the answer is wrong

### Provide any additional context or information

输入：
#Role: You are a data analyst experienced in SQL languages.
#Task: You will be provided a natural language question asked by users,please convert it to a SQL query so that relevant data could be returned by executing the SQL query against underlying database.
#Rules:1.ALWAYS generate column specified in the `Schema`, DO NOT hallucinate.2.ALWAYS specify date filter using `>`,`<`,`>=`,`<=` operator.3.ALWAYS calculate the absolute date range by yourself.4.DO NOT include date filter in the where clause if not explicitly expressed in the `Question`.5.DO NOT miss the AGGREGATE operator of metrics, always add it if needed.6.ONLY respond with the converted SQL statement.
#Exemplars:
#Question:超音数近12个月访问人数 按部门 #Schema:Table=[超音数产品], Metrics=[<访问次数 ALIAS 'pv' COMMENT '一段时间内用户的访问次数' AGGREGATE 'SUM'>,<访问用户数 ALIAS 'UV,访问人数,' COMMENT '访问的用户个数' AGGREGATE 'COUNT'>,<人均访问次数 ALIAS '平均访问次数,' COMMENT '每个用户平均访问的次数'>], Dimensions=[<部门>], Values=[] #SideInfo:CurrentDate=[2022-11-06] #SQL:SELECT 部门, 数据日期, 访问人数 FROM 超音数产品 WHERE 数据日期 >= '2021-11-06' AND 数据日期 <= '2022-11-06'
#Question:过去半个月忠实用户有哪一些 #Schema:Table=[超音数产品], Metrics=[<访问次数 ALIAS 'pv' COMMENT '一段时间内用户的访问次数' AGGREGATE 'SUM'>], Dimensions=[<用户>], Values=[] #SideInfo:CurrentDate=[2023-09-15],DomainTerms=[<忠实用户 COMMENT '一段时间内总访问次数大于100的用户'>] #SQL:SELECT 用户 FROM 超音数产品 WHERE 数据日期 >= '2023-09-01' AND 数据日期 <= '2023-09-15' GROUP BY 用户 HAVING SUM(访问次数) > 100
#Question:超音数本月pv最高的用户有哪些 #Schema:Table=[超音数产品], Metrics=[<访问次数 ALIAS 'pv' COMMENT '一段时间内用户的访问次数' AGGREGATE 'SUM'>], Dimensions=[<用户>], Values=[] #SideInfo:CurrentDate=[2023-08-31],DomainTerms=[<核心用户 COMMENT '用户为tom和lucy'>] #SQL:SELECT 用户 FROM 超音数产品 WHERE 数据日期 >= '2023-08-01' AND 数据日期 <= '2023-08-31' ORDER BY 访问次数 DESC LIMIT 1
#Question:超音数访问时长小于1小时，且来自美术部的用户是哪些 #Schema:Table:[超音数产品], Metrics:[<访问时长 COMMENT '一段时间内用户的访问时长' AGGREGATE 'SUM'>], Dimensions:[<用户>], Values:[<部门='美术部'>] #SideInfo:CurrentDate=[2023-07-31],DomainTerms=[<核心用户 COMMENT '用户为tom和lucy'>] #SQL:SELECT 用户 FROM 超音数产品 WHERE 部门 = '美术部' AND 访问时长 < 1
#Question:超音数访问次数大于1k的部门是哪些 #Schema:Table=[超音数产品], Metrics=[<访问次数 ALIAS 'pv' COMMENT '一段时间内用户的访问次数' AGGREGATE 'SUM'>], Dimensions=[<部门>], Values=[] #SideInfo:CurrentDate=[2023-09-14] #SQL:SELECT 部门 FROM 超音数产品 WHERE 访问次数 > 1000
#Question:7月销售部的收入 #Schema:Table=[财务现金流量数据集], Metrics=[<收入 COMMENT '收入' AGGREGATE 'SUM'>], Dimensions=[], Values=[] #SideInfo:CurrentDate=[2024-08-16] #SQL:

输出：
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "#Question" <S_IDENTIFIER>
    at line 1, column 1.

Was expecting one of:

    "("
    "ALTER"
    "ANALYZE"
    "BEGIN"
    "CALL"
    "COMMENT"
    "COMMIT"
    "CREATE"
    "DECLARE"
    "DELETE"
    "DESCRIBE"
    "DROP"
    "EXEC"
    "EXECUTE"
    "EXPLAIN"
    "GRANT"
    "IF"
    "INSERT"
    "MERGE"
    "PURGE"
    "RENAME"
    "REPLACE"
    "RESET"
    "ROLLBACK"
    "SAVEPOINT"
    "SET"
    "SHOW"
    "TRUNCATE"
    "UPDATE"
    "UPSERT"
    "USE"
    "VALUE"
    "VALUES"
    "WITH"
    <K_SELECT>

	at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:37141)
	at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:36968)
	at net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:312)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil$1.call(CCJSqlParserUtil.java:304)
	at net.sf.jsqlparser.parser.CCJSqlParserUtil$1.call(CCJSqlParserUtil.java:301)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	... 1 common frames omitted

**Comment by jerryjzhang** [comment]
It seems llama3.1 doesn't follow the instruction. I will try if there is any workaround.

**Comment by jerryjzhang** [comment]
@jdzhang1221 你好，llama3.1:8b在master版本验证已经可以了
