### ISSUE TITLE
[Enhancement] 现在的下钻都是基于规则语义解析才能触发，希望增加基于大模型语义解析的下钻

### ISSUE THREAD

**Issue by a542197095** [tencentmusic/supersonic#1575]
### Search before asking

- [X] I had searched in the [issues](https://github.com/tencentmusic/supersonic/issues?q=is%3Aissue) and found no similar issues.

### Description

现在的下钻都是基于规则语义解析才能触发，希望增加基于大模型语义解析的下钻

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by jerryjzhang** [comment]
不是特别明白，目前大模型解析也是可以下钻的，取决于大模型如何理解问题语义
