### ISSUE TITLE
[Feature] 核心流程PlantUML时序图

### ISSUE THREAD

**Issue by whyuds** [tencentmusic/supersonic#1589]
### Search before asking

- [X] I had searched in the [issues](https://github.com/tencentmusic/supersonic/issues?q=is%3Aissue) and found no similar issues.

### Description

整体代码复杂度高，层级深，对于不了解项目的人来说定位问题、生成策略较为困难，过度依赖低效的debug。
正在梳理PlantUML时序图，能够加快对项目的理解，快速介入使用、开发。通过PlantUML插件提供的代码跳转、文件跳转功能，快速定位代码以了解更详细逻辑策略。
目前又一些无法想象应用场景的，或者解决CornerCase，历史遗留代码，由于缺少注释理解较为困难。个人能力、精力有限希望社区合作支持，一起补充

![Execute-0](https://github.com/user-attachments/assets/5bddc68e-8ff0-4d3a-a41b-5aa168c4990a)

![Mapper阶段_EmbeddingMapper_doMap-0](https://github.com/user-attachments/assets/13acbeec-bf42-4a3b-9549-a14ce6f96b5a)

![Parse阶段_LLMSqlParser_parse-0](https://github.com/user-attachments/assets/bf7bb097-936b-4221-b2f2-0b346aa21ab4)

### Use case

完善文档

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by whyuds** [comment]
可以考虑单独建文档项目或者合入主干某文档目录

**Comment by dawsongzhao0523** [comment]
刚开始参加项目时，我也困扰过。但是，慢慢熟悉了项目后，好像没有这个问题了。整理成文档也有不太好的地方，就是代码在快速迭代。文档跟不上代码迭代速度。

**Comment by dawsongzhao0523** [comment]
> 可以考虑单独建文档项目或者合入主干某文档目录

确实项目还缺少专门的开发指南和手册。原始团队也挺忙的。

**Comment by whyuds** [comment]
> > 可以考虑单独建文档项目或者合入主干某文档目录
> 
> 确实项目还缺少专门的开发指南和手册。原始团队也挺忙的。

这个理解，能提供下答疑解惑我这边也可以自己补充进去。目前写了一部分

**Comment by jdzhang1221** [comment]
> 可以考虑单独建文档项目或者合入主干某文档目录

https://github.com/supersonicbi/supersonicbi.github.io 放这个文档里吗

**Comment by jdzhang1221** [comment]
> 刚开始参加项目时，我也困扰过。但是，慢慢熟悉了项目后，好像没有这个问题了。整理成文档也有不太好的地方，就是代码在快速迭代。文档跟不上代码迭代速度。

确实，代码每次更新都需要有人去更新文档，或者需要有人来推广，让更多的开发者参与进来

**Comment by whyuds** [comment]
> > 刚开始参加项目时，我也困扰过。但是，慢慢熟悉了项目后，好像没有这个问题了。整理成文档也有不太好的地方，就是代码在快速迭代。文档跟不上代码迭代速度。
> 
> 确实，代码每次更新都需要有人去更新文档，或者需要有人来推广，让更多的开发者参与进来

所以感觉用可以方便定位到代码的流程图更合适。较粗粒度的指向性文档减少文档维护成本，类似本项目的密集的规则通过跳转到具体代码再进行分析

**Comment by jerryjzhang** [comment]
非常感谢，我来仔细看一下，其实是嵌入到文档中心里
