### ISSUE TITLE
[question] 如何修改密码，就是不知道前端密码是怎么加密的？

### ISSUE THREAD

**Issue by aiwenForGit** [tencentmusic/supersonic#1591]
### Describe your question

问下，如何修改密码，api方式下如何将用户的密码认证，涉及到加密算法，没有搞明白目前的机制，还请作者帮忙解释下，多谢！

**Comment by dawsongzhao0523** [comment]
0.9.8版本，我们可以贡献一个修改密码的PR。
![image](https://github.com/user-attachments/assets/e55885ce-1aeb-49a3-b26e-56d91fda85d0)

**Comment by jerryjzhang** [comment]
> 0.9.8版本，我们可以贡献一个修改密码的PR。 ![image](https://private-user-images.githubusercontent.com/133857587/367512261-e55885ce-1aeb-49a3-b26e-56d91fda85d0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY5MTQ0ODYsIm5iZiI6MTcyNjkxNDE4NiwicGF0aCI6Ii8xMzM4NTc1ODcvMzY3NTEyMjYxLWU1NTg4NWNlLTFhZWItNDlhMy1iMjZlLTU2ZDkxZmRhODVkMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyMVQxMDIzMDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ZjkzNjBkMGIyZWIyMDU0OGI2MjMyZjAyOTZjYTUzMTMzNGFlMjg2MjA4MWEyYTA5Mjk1YTgxNTc3ZjhhMjg3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.PN3PkskgRYDPN8o4J3EbEfakkca31gR-V-LS-8nrypg)

收到，期待

**Comment by aiwenForGit** [comment]
@jerryjzhang [这个有点不是很明白，作者不是更清楚实现原理吗](url) #

**Comment by jerryjzhang** [comment]
> @jerryjzhang [这个有点不是很明白，作者不是更清楚实现原理吗](url) #

目前没有实现密码变更的功能哈
