### ISSUE TITLE
[question] 指标市场菜单下面没有新建指标的控件

### ISSUE THREAD

**Issue by fengbaoli** [tencentmusic/supersonic#1592]
### Describe your question

使用的docker部署的，版本为0.9.4版本，但是新建指标的时候没有发现新建指标控件，只有批量操作的控件

### Your environment

版本为0.9.4版本，centos7的操作系统

**Comment by fengbaoli** [comment]
![Uploading 截图.png…]()

**Comment by jerryjzhang** [comment]
截图好像上传失败了

**Comment by jerryjzhang** [comment]
指标市场当前是面向业务用户去发现指标，创建指标是在语义建模中
