### ISSUE TITLE
[question] 有关术语的联想失效

### ISSUE THREAD

**Issue by WaizLi** [tencentmusic/supersonic#1595]
### Describe your question

创建好了相关数据集，并定义了一些术语，第一天提问时联想还能出来，第二天再验证时，联想无效了，看search这个接口响应数据是空的；出现这个问题后，相关术语的咨询也无效了，这种场景要如何解决？是否是内置缓存的问题

**Comment by lexluo09** [comment]
感谢反馈这个问题，我们定位一下

**Comment by WaizLi** [comment]
已收到！

**Comment by jerryjzhang** [comment]
bug应该已经修复

**Comment by WaizLi** [comment]
已收到！
