### ISSUE TITLE
[question] Mysql连接失败

### ISSUE THREAD

**Issue by gzcharles** [tencentmusic/supersonic#1604]
### Describe your question

0.9.6 docker部署，本地mysql 8.0，创建数据库连接，jdbc:mysql://localhost:3306/my_db，连接测试每次都失败，请问如何解决？

**Comment by ZHUxjj** [comment]
0.9.6的  data-mysql.sql  里面只有两个案例的测试数据，其他后台配置的数据都是空的。

**Comment by jerryjzhang** [comment]
麻烦试一下mysql 5.0版本试试

**Comment by gzcharles** [comment]
错了，在容器中连接本地机不是localhost，要用宿主机的ip，另外要开放mysql远程连接的权限。

**Comment by Nacime322** [comment]
请问怎么开放mysql远程连接的权限，宿主机的ip是公网ip吗
