### ISSUE TITLE
[Enhancement] 推荐的数据集不准，计算规则需要改进

### ISSUE THREAD

**Issue by ylhh353** [tencentmusic/supersonic#1614]
### Search before asking

- [X] I had searched in the [issues](https://github.com/tencentmusic/supersonic/issues?q=is%3Aissue) and found no similar issues.

### Description

推荐数据集不准确，有相似表，不容易进行推荐准确的表

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by jerryjzhang** [comment]
已经做了优化，请拉最新代码再试试
