### ISSUE TITLE
[Enhancement] 希望调/api/chat/query/search 时  如果前端选中推荐的数据集后，能加个按钮不， 是否按选中的数据集进行解析得到sql 结果，不然这个api作用比较小。

### ISSUE THREAD

**Issue by ylhh353** [tencentmusic/supersonic#1616]
### Search before asking

- [X] I had searched in the [issues](https://github.com/tencentmusic/supersonic/issues?q=is%3Aissue) and found no similar issues.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by jerryjzhang** [comment]
这个以前讨论过，如果用户显式选择了某个数据集的联想词，则后续查询都限定在该数据集。 @williamhliu 看看
