### ISSUE TITLE
你好 经过几天尝试 还是没解决 希望可以解答 关于IDE 启动source code，配置好了mysql

### ISSUE THREAD

**Issue by hengherui** [tencentmusic/supersonic#1618]
### Describe your question

如题，配置好了mysql，但是启动项目，一直报错
![image](https://github.com/user-attachments/assets/918fcf1a-f0fb-4ac3-a2bd-86ec05d5763d)
如图application-local.yaml 配置好了mysql，windows 开启mysql 数据库是data
但是项目启动一直报入下错：说data 没有s2_database表，y也没有s2_chat_memory，本地mysql 确实没有这些表，那哪里去修改这些报错呢，希望能得到解答
![image](https://github.com/user-attachments/assets/3448efef-4a68-438c-b776-f5a30176224f)
![image](https://github.com/user-attachments/assets/f3122135-b11b-49f4-8432-a0f783f91a1d)

### Your environment

windows idea

**Comment by lexluo09** [comment]
<img width="415" alt="企业微信截图_93091913-82b0-4f19-9bcc-adf8cd4e160b" src="https://github.com/user-attachments/assets/871905b5-64a2-4ba8-853c-da242b5db0de">
你好，执行一下这两个脚步初始化数据

**Comment by hengherui** [comment]
解决了 谢谢 @lexluo09

**Comment by hengherui** [comment]
![image](https://github.com/user-attachments/assets/e52474bf-fd6e-4995-afbd-1bf666eee786)
你好 我已经弄好了数据 和智能助手，在问答中，我怎么取消对于日期的限制，即去掉where条件呢，就是不设置where 查询
![image](https://github.com/user-attachments/assets/aace63cd-f5c4-4084-9481-908116521fd9)

实际上选择字段 我没有选择数据日期

**Comment by lexluo09** [comment]
在数据集中将数据日期去掉即可

**Comment by hengherui** [comment]
请问这个数据日期是自带的吗 我的数据集根本没有数据日期这个字段
![image](https://github.com/user-attachments/assets/7e685f65-60df-4104-8148-d56388f85086)
我只选了运单号和中转分拨名称
![image](https://github.com/user-attachments/assets/a05fa681-a044-4e7c-abd2-418fd8fc5bd6)
datasource error : 1_data_chunk_0 miss identifier，请问自己的这个数据集报错miss identifier是什么问题啊

**Comment by lexluo09** [comment]
> 请问这个数据日期是自带的吗 我的数据集根本没有数据日期这个字段 ![image](https://private-user-images.githubusercontent.com/26928124/363460428-7e685f65-60df-4104-8148-d56388f85086.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyNTc5NzUsIm5iZiI6MTcyNTI1NzY3NSwicGF0aCI6Ii8yNjkyODEyNC8zNjM0NjA0MjgtN2U2ODVmNjUtNjBkZi00MTA0LTgxNDgtZDU2Mzg4Zjg1MDg2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAyVDA2MTQzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY0ZDc2NTNiOWI2NTFiZmNmZmFjZTBjOWNhMjljMTc5YWI2MTgxOTU3MDUxMTdhNTBhZDg4YTE4N2M0M2YxMDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Vhmmt3LPTseLRXc_G_ydp95dJQ1oHhCpr4P3iRJlTns) 我只选了运单号和中转分拨名称 ![image](https://private-user-images.githubusercontent.com/26928124/363468028-a05fa681-a044-4e7c-abd2-418fd8fc5bd6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyNTc5NzUsIm5iZiI6MTcyNTI1NzY3NSwicGF0aCI6Ii8yNjkyODEyNC8zNjM0NjgwMjgtYTA1ZmE2ODEtYTA0NC00ZTdjLWFiZDItNDE4ZmQ4ZmM1YmQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAyVDA2MTQzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk2MjAwOTMyYjcwZDI4MDk4MGYyOTE1ZWY4OGRhNjlmNWM5MWJlYTMyZTNjMjMzN2NhNGFiNWE3NGExMDg1MzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jydKgVXv3jbKy7sJU1Czy18aLahI7YOreWuNfBAf8Ec) datasource error : 1_data_chunk_0 miss identifier，请问自己的这个数据集报错miss identifier是什么问题啊

请问你使用的是哪个版本，用最新版本应该没有这个问题

**Comment by jerryjzhang** [comment]
最新的版本，如果数据集中没有分区日期的维度，就不会带上了
