### ISSUE TITLE
[Bug]  纬度值自动填充时如果纬度值太多，在点击完成时就会报错，应该只截取topN条 

### ISSUE THREAD

**Issue by qfikh** [tencentmusic/supersonic#1620]
### Search before asking

- [X] I had searched in the [issues](https://github.com/tencentmusic/supersonic/issues?q=is%3Aissue) and found no similar issues.

### Version

0.9.6

### What's Wrong?

纬度值自动填充时如果纬度值太多，在点击完成时就会报错，应该只截取topN条   com/tencent/supersonic/headless/server/service/impl/DimensionServiceImpl.java:338

### What You Expected?

纬度值自动填充时如果纬度值太多，在点击完成时就会报错，应该只截取topN条   com/tencent/supersonic/headless/server/service/impl/DimensionServiceImpl.java:338

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by daikon12** [comment]
Thanks for your feedback. Could you please send me the specific error message?
@qfikh

**Comment by daikon12** [comment]
@qfikh  The default demo scene supported used the model gpt-3.5-turbo before, with a maximum length of 1000 tokens. It has now been updated to gpt-4o-mini, with a maximum length of 5000 tokens.  If you wish to use more, please use your own OpenAI API key, It can solve the token too long error problem。please refer to：
https://github.com/tencentmusic/supersonic/pull/1641
