### ISSUE TITLE
[Enhancement] 模型权限控制

### ISSUE THREAD

**Issue by smlHao** [tencentmusic/supersonic#1625]
### Search before asking

- [X] I had searched in the [issues](https://github.com/tencentmusic/supersonic/issues?q=is%3Aissue) and found no similar issues.

### Description

能生成sql，模型权限控制时不够精确，希望能根据sql用到的模型进行权限控制。
例如一个数据集下有m1、m2、m3、m4四个模型、sql里只用到m1、m2模型，如果没有给m3、m4赋权,就会提示m3、m4没权限

![image](https://github.com/user-attachments/assets/88af3816-83b3-49fc-a97c-bc842f8307e4)

![image](https://github.com/user-attachments/assets/c36000aa-e6ce-40c6-84a0-cf6bf92105e4)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by jerryjzhang** [comment]
谢谢反馈，我们来优化
