### ISSUE TITLE
[Enhancement] 【问答对话】Schema Mapping规则优化

### ISSUE THREAD

**Issue by jerryjzhang** [tencentmusic/supersonic#1637]
### Search before asking

- [X] I had searched in the [issues](https://github.com/tencentmusic/supersonic/issues?q=is%3Aissue) and found no similar issues.

### 一个detect word仅能映射一个similarity=1.0语义对象，且更长的detect word优先。
举例：
Question: 超音数近30天人均访问次数
指标池：访问次数、人均访问次数
期望映射：人均访问次数
解释：【访问次数】和【人均访问次数】都能映射为similarity=1.0，但是detect word【访问次数】只能映射其中一个，且【人均访问次数】长度更长，优先映射。
 
### 一个detect word若可以映射similarity=1.0语义对象，则不映射similarity<1.0语义对象
举例：
Question: 超音数近30天访问次数
指标池：访问次数、人均访问次数
期望映射：访问次数
解释：【访问次数】similarity=1.0，【人均访问次数】similarity=0.66，不会映射后者

### 一个detect word若映射不到similarity=1.0语义对象，则可以映射多个similarity<1.0语义对象
举例：
Question: 超音数近30天访问次数
指标池：总计访问次数、人均访问次数
期望映射：总计访问次数、人均访问次数
解释：【总计访问次数】similarity=0.66，【人均访问次数】similarity=0.66，没有similarity=1.0的指标，则可映射多个<1.0的。

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by dawsongzhao0523** [comment]
<img width="1177" alt="image" src="https://github.com/user-attachments/assets/03d63fba-12f6-497c-a16a-01e9a2f644e4">
我们现在也在探索mapper映射问题，如果mapper不准后面的流程意义不大。我们那尝试将模糊的问题交给用户去选择。同时开发【用户管理】-【偏好设置】功能，将用户对指标和维度的选择习惯存储起来。感觉内置规则，很难覆盖用户的特殊需求。

**Comment by jerryjzhang** [comment]
> <img alt="image" width="1177" src="https://private-user-images.githubusercontent.com/133857587/365090899-03d63fba-12f6-497c-a16a-01e9a2f644e4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxNTUwODgsIm5iZiI6MTcyNjE1NDc4OCwicGF0aCI6Ii8xMzM4NTc1ODcvMzY1MDkwODk5LTAzZDYzZmJhLTEyZjYtNDk3Yy1hMTZhLTAxZTlhMmY2NDRlNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxMlQxNTI2MjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZWY4ZjljY2MxMGVjNWM1ZDIxOTJjYzYwYmVlYzUyNzAxYmI1MmY2NGVmZGE5Y2UwYWRlZWNhZWRhYzAwNjc0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.6-FfdMFraqwAYJd7prWLsgQRWwy5Lzmh5tDunNno5pY"> 我们现在也在探索mapper映射问题，如果mapper不准后面的流程意义不大。我们那尝试将模糊的问题交给用户去选择。同时开发【用户管理】-【偏好设置】功能，将用户对指标和维度的选择习惯存储起来。感觉内置规则，很难覆盖用户的特殊需求。

这个确实也是一个思路，不过从我们的实践场景看起来，用户不太会去做选择题，只想要答案。当然，这个可以作为一种选项，可以在助理上选择开启与否。

**Comment by jerryjzhang** [comment]
欢迎后续将此功能贡献进来!
