### ISSUE TITLE
[Bug] 【问答对话】当分区时间字段名不为imp_date时，前端筛选时间重新查询不生效

### ISSUE THREAD

**Issue by jerryjzhang** [tencentmusic/supersonic#1638]
### Search before asking

- [X] I had searched in the [issues](https://github.com/tencentmusic/supersonic/issues?q=is%3Aissue) and found no similar issues.

### Version

0.9.8

### What's Wrong?

![image](https://github.com/user-attachments/assets/202989e2-edc8-4b42-9cf2-859c2e6c92e1)
有用户反馈只有当把分区时间字段名改为imp_date，重新查询才会生效

### What You Expected?

修复问题

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by lxwcodemonkey** [comment]
我看下
