### ISSUE TITLE
[Enhancement]【语义查询】最终SQL嵌套层数过多，优化生成逻辑

### ISSUE THREAD

**Issue by mxli441** [tencentmusic/supersonic#1640]
### Search before asking

- [X] I had searched in the [issues](https://github.com/tencentmusic/supersonic/issues?q=is%3Aissue) and found no similar issues.

### Description

在现有的机制中，最终的SQL，一条简单的SQL嵌套多达四至五层之多，这对于将来多表关联来说，实在是过于冗余，且可读性不好，是否可以对这一块进行简化，否则，这块将成为问题SQL，排在优化第一行
WITH t_201 AS (
  SELECT
    COL264,
    sys_imp_month,
    ADD_MON,
    ADD_YEAR
  FROM
    (
      SELECT
        COL264,
        sys_imp_month,
        second_ADD_MON AS ADD_MON,
        second_ADD_YEAR AS ADD_YEAR
      FROM
        (
          SELECT
            second_ADD_MON,
            second_ADD_YEAR,
            COL264,
            sys_imp_month,
            STAT_DATE
          FROM
            (
              SELECT
                ADD_MON AS second_ADD_MON,
                ADD_YEAR AS second_ADD_YEAR,
                COL264 AS COL264,
                TO_CHAR(TO_DATE(STAT_DATE, 'YYYYMMDD'), 'YYYY-MM') sys_imp_month,
                STAT_DATE AS STAT_DATE
              FROM
                (
                  SELECT
                    *
                  FROM
                     table1_1
                )
            )
        )
    )
)
SELECT
  COL264 AS COL264,
  SUM(ADD_MON) AS ADD_MON
FROM
  t_201
WHERE
  COL264 = '48'
  AND sys_imp_month = '2024-06'
GROUP BY
  COL264
ORDER BY
  ADD_MON DESC

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by jerryjzhang** [comment]
确认一下，是否后续会提PR呢？

**Comment by mxli441** [comment]
先确认下你们官方是不是已在构造中

**Comment by jerryjzhang** [comment]
还没有，欢迎提PR










在 2024-09-10 08:50:31，"mxli441" ***@***.***> 写道：

先确认下你们官方是不是已在构造中

**Comment by jerryjzhang** [comment]
@mxli441 hello，请问是否会提交PR，我们在做版本规划中

**Comment by mxli441** [comment]
我们可以提交

**Comment by mxli441** [comment]
如何提交pr
