### ISSUE TITLE
新人学习求助

### ISSUE THREAD

**Issue by Learner-feng** [tencentmusic/supersonic#1642]
![企业微信截图_1725899706307](https://github.com/user-attachments/assets/99189224-c0ff-47ae-abb8-bc7e4d48b1c3)

示例中的这个维度值是在哪里设置

**Comment by Learner-feng** [comment]
在维度管理-维度值设置-设置可见，搜索的时候还是无法看到维度值

**Comment by jerryjzhang** [comment]
维度值可见后，还需要系统成功导入维度值到字典，有可能当中出问题了

**Comment by dawsongzhao0523** [comment]
还是需要有一个界面能够查看维度值
