### ISSUE TITLE
[Bug] embedding retrievals should not sort by distance reversed

### ISSUE THREAD

**Issue by zhouzj1610** [tencentmusic/supersonic#1644]
### Search before asking

- [X] I had searched in the [issues](https://github.com/tencentmusic/supersonic/issues?q=is%3Aissue) and found no similar issues.

### Version

master branch

### What's Wrong?

in file common/service/impl/EmbeddingServiceImpl.java, the embedding retrievals should not sorted by distance reversed, because the smaller the distance, the more similar it is.
Should remove the ".reversed()":
![image](https://github.com/user-attachments/assets/5870d672-0de5-4148-bd51-d476831df77b)

### What You Expected?

Should remove the ".reversed()" from function retrieveSingleQuery in file common/service/impl/EmbeddingServiceImpl.java.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by lexluo09** [comment]
嗯嗯，前面的maxResults已经限制了，这里应该不影响结果；我正好在统一重构这部分代码，为了避免歧义，我统一将distance改成similarity；

https://github.com/tencentmusic/supersonic/issues/1637
![image](https://github.com/user-attachments/assets/1e4dd27f-af81-49cc-b4a6-eaa3b54f87d9)

**Comment by zhouzj1610** [comment]
如果改成similarity，那在排序时应该加上reversed()吧？最相似的排在最前面，然后取前num个。

而且我觉得在search里通过maxResults限制的逻辑不太合理，应该都计算完相似性之后，按相似性从大到小排序，再选前num个
