### ISSUE TITLE
[Bug] 连接clickhouse数据库成功，在查询数据库时，没有创建最终SQL执行的步骤，导致查询失败

### ISSUE THREAD

**Issue by TZJ12** [tencentmusic/supersonic#1657]
### Search before asking

- [X] I had searched in the [issues](https://github.com/tencentmusic/supersonic/issues?q=is%3Aissue) and found no similar issues.

### Version

今天拉取的源码编译最新版本

### What's Wrong?

连接clickhouse数据库成功，创建模型，创建数据集，新建助理，添加语义解析工具成功，但是在查询数据库内容时，没有创建最终SQL执行的步骤，导致查询失败，这是为什么呢
![8CF46A5E-E45D-41c0-BA23-944201641B4A](https://github.com/user-attachments/assets/425788bc-fa2e-4af7-939a-d14c95c40366)
下面是日志报错内容:
![lQLPKc8rCrIwWavNAoLNBuuw9f6BQ7C90dMGywKGR2ieAA_1771_642](https://github.com/user-attachments/assets/725710b0-3e09-4f2c-855d-0dfc5db7a491)
![lQLPKIINLj9t-qvNAarNBxawVOH9eJfRCfEGywKGScmUAA_1814_426](https://github.com/user-attachments/assets/13c9cee6-2062-4458-a3e2-4f25e5d651c5)

### What You Expected?

希望能够有最终SQL执行，并且成功查询

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by lexluo09** [comment]
这里可以在界面导出日志看看，看起来是生成执行SQL时报错了
