### ISSUE TITLE
[question] 关于维度的别名设置是否会混淆？

### ISSUE THREAD

**Issue by WaizLi** [tencentmusic/supersonic#1671]
### Describe your question

设置了两个字段
名称：活动名称，别名：活动
名称：活动id，别名：活动编号
问题：每个活动的参与人数？

最终生成的sql，SELECT的是活动ID，并非活动名称

![image](https://github.com/user-attachments/assets/5fe4649d-3288-40ec-9ea6-00cd51a665d9)
![image](https://github.com/user-attachments/assets/88ad9fb6-9daa-4c33-a77b-cf7a3bd1d0e4)

**Comment by lexluo09** [comment]
这个我们确认一下，理论上是要生成"活动名称"，可能需要看看Mapper阶段识别的element是哪个

**Comment by WaizLi** [comment]
已收到！

**Comment by lexluo09** [comment]
你好，可以截图看看Mapper阶段识别的element是哪个吗
