### ISSUE TITLE
[Enhancement] 【问答对话】兼容适配大模型SQL输出

### ISSUE THREAD

**Issue by jerryjzhang** [tencentmusic/supersonic#1675]
### Search before asking

- [X] I had searched in the [issues](https://github.com/tencentmusic/supersonic/issues?q=is%3Aissue) and found no similar issues.

### Description

采用qwen2:7b模型时，生成SQL在字段名上加``，导致后续解析异常，需要进行兼容适配。

<img width="1422" alt="image" src="https://github.com/user-attachments/assets/4fc9eadd-2d53-4de1-9e39-697ef87f0a5a">

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by lexluo09** [comment]
已兼容修复

![image](https://github.com/user-attachments/assets/a7122017-8a91-4d7f-87b0-bf5d67ca9943)

![image](https://github.com/user-attachments/assets/a0d90dea-fe72-43d8-8097-93a5f6394972)
