### ISSUE TITLE
[question] Windows下，源码编译启动不成功

### ISSUE THREAD

**Issue by 15074852943** [tencentmusic/supersonic#1676]
### Describe your question

windows环境，源码0.9.8版本编译启动不成功，报错日志如下：
![image](https://github.com/user-attachments/assets/d4ab7e4e-c58a-40b1-8bee-0ab651a8d3af)
![image](https://github.com/user-attachments/assets/5e3de8dc-6a94-47d1-bb0f-bc24ebf24278)

### Your environment

Windows，supersonic 0.9.8，jdk 1.8

### Screenshots or Logs

[error.chat.log](https://github.com/user-attachments/files/17001681/error.chat.log)
[info.chat.log](https://github.com/user-attachments/files/17001682/info.chat.log)

**Comment by jerryjzhang** [comment]
这个基本上是本地环境的问题哈，不是源码问题，建议搜一下NoClassDefFoundError类异常如何解决处理
