### ISSUE TITLE
[Bug] 无法手动创建维度

### ISSUE THREAD

**Issue by zhouhongyu888** [tencentmusic/supersonic#1685]
### Search before asking

- [X] I had searched in the [issues](https://github.com/tencentmusic/supersonic/issues?q=is%3Aissue) and found no similar issues.

### Version

0.9.6

### What's Wrong?

创建完模型之后，进入模型想要补充创建维度，填完信息，点击完成没有反应
![image](https://github.com/user-attachments/assets/fa6f9ce4-fa75-4faf-8837-4a9431acbea3)

### What You Expected?

修复不能手动创建维度的问题

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by lxwcodemonkey** [comment]
拉下新代码试试 commit #1668已修复 或者cherry-pick
