### ISSUE TITLE
联想失效

### ISSUE THREAD

**Issue by upeakAll** [tencentmusic/supersonic#1686]
### Describe your question

创建好了相关数据集，维度配置了一些维度值，之前提问时可以联想出相关的指标、维度，但是现在联想无效了，我看api/chat/query/search这个接口响应数据是空的，没有出现报错信息

**Comment by jerryjzhang** [comment]
可以拉master代码再试试吗？另一个issue发现BUG已修复

**Comment by lexluo09** [comment]
可以拉最新代码试试看看，我这边看已经可以了

https://github.com/tencentmusic/supersonic/issues/1686
