### ISSUE TITLE
[Enhancement] 记忆中的相似性fewshot问题找回优化

### ISSUE THREAD

**Issue by zhouhongyu888** [tencentmusic/supersonic#1691]
### Search before asking

- [X] I had searched in the [issues](https://github.com/tencentmusic/supersonic/issues?q=is%3Aissue) and found no similar issues.

### Description

相似性很高的历史问答无法作为fewshot被召回，目前召回的大多数是默认的fewshot
![image](https://github.com/user-attachments/assets/99e82b6d-768b-4fa0-b3a3-395c1b067137)
![image](https://github.com/user-attachments/assets/d1237c65-4ab3-41a1-b0a9-d72f7d31b5fc)

### Solution

希望可以优化相似性的计算逻辑

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by jerryjzhang** [comment]
助理中已启用的记忆个数有多少？

**Comment by lexluo09** [comment]
好的，我看看

**Comment by zhouhongyu888** [comment]
> 助理中已启用的记忆个数有多少？

启用了10个

**Comment by lexluo09** [comment]
你好，代码用的是哪个版本

**Comment by lexluo09** [comment]
我这边复现了，原因是从记忆管理中只召回5个；但是在OnePassSCSqlGenStrategy中召回数是10个，所有还会有5个从默认的examplar中召回，还会存在默认的fewshot召回，我们修复一下

**Comment by lexluo09** [comment]
我们修复一下

**Comment by zhouhongyu888** [comment]
> 我这边复现了，原因是从记忆管理中只召回5个；但是在OnePassSCSqlGenStrategy中召回数是10个，所有还会有5个从默认的examplar中召回，还会存在默认的fewshot召回，我们修复一下

好的，这个太重要了，相似度极高的问题如果没有召回，就极大损失了准确性

**Comment by lexluo09** [comment]
已优化，拉取最新代码试试，如果还有问题帮忙再反馈哈，谢谢～
