### ISSUE TITLE
[Enhancement] 感觉准确率有点低，大模型对语义的理解有误

### ISSUE THREAD

**Issue by 15074852943** [tencentmusic/supersonic#1701]
### Search before asking

- [X] I had searched in the [issues](https://github.com/tencentmusic/supersonic/issues?q=is%3Aissue) and found no similar issues.

### Description

针对以下问题，应该要怎么去优化呢？

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by jerryjzhang** [comment]
你好，需要把数据集的指标和维度也截图看一下

**Comment by 15074852943** [comment]
> 你好，需要把数据集的指标和维度也截图看一下
您好，模型管理如下：
![image](https://github.com/user-attachments/assets/25862c42-6115-4483-a5f8-71daff43864f)
![image](https://github.com/user-attachments/assets/d81a796b-4821-4700-909c-3bf24c75afe9)
![image](https://github.com/user-attachments/assets/9516389c-870e-496e-9835-18160ee906c7)

数据集管理如下图：
![image](https://github.com/user-attachments/assets/52ac2917-2f12-4675-8d8a-c61664263533)
![image](https://github.com/user-attachments/assets/2bcc14e5-c293-44ed-aef3-a4d2132504e8)

**Comment by 15074852943** [comment]
> 你好，需要把数据集的指标和维度也截图看一下

是否是模型配置有问题？要怎样准确配置呢？

**Comment by jerryjzhang** [comment]
男女员工数或者男女员工比例，这个需要定义具体的指标，目前还做不到让大模型理解多层的含义

**Comment by 15074852943** [comment]
> 男女员工数或者男女员工比例，这个需要定义具体的指标，目前还做不到让大模型理解多层的含义

感觉似乎是大模型对语义的理解很不好，如何能够提高呢，
![image](https://github.com/user-attachments/assets/9cbeaf43-f7c6-454d-acec-24735ceca94f)

我使用的是open ai，gpt-4o模型，配置如下：
![image](https://github.com/user-attachments/assets/c968e927-e702-4d00-a177-52b590ac6ec6)

 系统设置配置如下：
![image](https://github.com/user-attachments/assets/a795cae0-ad29-4fee-8980-e9760a723b65)

**Comment by 15074852943** [comment]
1
