### ISSUE TITLE
[Bug] 物理sql生成正确，程序执行查询报错

### ISSUE THREAD

**Issue by zhouhongyu888** [tencentmusic/supersonic#1706]
### Search before asking

- [X] I had searched in the [issues](https://github.com/tencentmusic/supersonic/issues?q=is%3Aissue) and found no similar issues.

### Version

使用的最新版本的docker镜像

### What's Wrong?

如下图的提问，可以正常生成s2sql以及物理sql，去数据库也能正常查询出结果，但是就是程序报错了
看报错信息，推测可能是先去缓存中取数校验导致的
![image](https://github.com/user-attachments/assets/4be28f7f-71af-4521-a8d2-fbdc3ce49eb7)
![image](https://github.com/user-attachments/assets/c2a41d62-c156-4f0b-a23c-68e98e99758d)

### What You Expected?

希望可以修复问题

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhouhongyu888** [comment]
神奇的是，我在问题中增加了一个指标，查询就通过了，单独查那一个指标怎么就不行
![image](https://github.com/user-attachments/assets/31317d2c-db8e-4298-a3fe-b4a8f7a55447)

**Comment by lexluo09** [comment]
纬度推荐空指针，这个问题已经修复了，可以拉最新代码试试

**Comment by zhouhongyu888** [comment]
> 纬度推荐空指针，这个问题已经修复了，可以拉最新代码试试

我看镜像包还没更新呀，可否更新下

**Comment by zhouhongyu888** [comment]
> 纬度推荐空指针，这个问题已经修复了，可以拉最新代码试试

昨天运行报错，同样的查询今天就又可以正常查询了

**Comment by lexluo09** [comment]
> > 纬度推荐空指针，这个问题已经修复了，可以拉最新代码试试
> 
> 我看镜像包还没更新呀，可否更新下

已经更新了，用最新latest版本，0.9.6版本不会打包后不会再更新了

**Comment by zhouhongyu888** [comment]
> > > 纬度推荐空指针，这个问题已经修复了，可以拉最新代码试试
> > 
> > 
> > 我看镜像包还没更新呀，可否更新下
> 
> 已经更新了，用最新latest版本，0.9.6版本不会打包后不会再更新了

![image](https://github.com/user-attachments/assets/a5504bc7-6857-4d2f-9e44-b5b990c6ffee)
我用的就是最新版本的

**Comment by lxwcodemonkey** [comment]
目前已经有判空处理了，应该不会有这个报错了，最近还有发现这个报错吗？
或者贴下这个指标配置的截图看看呢？以及最新的报错日志
