### ISSUE TITLE
[Feature] 新功能建议

### ISSUE THREAD

**Issue by lixueqian1982** [tencentmusic/supersonic#1710]
### Search before asking

- [X] I had searched in the [issues](https://github.com/tencentmusic/supersonic/issues?q=is%3Aissue) and found no similar issues.

### Description

移动端有联通飞书的计划吗？咱们这个产品建议添加用户水印功能，增加数据安全性。

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by jerryjzhang** [comment]
你好，感谢反馈，不过这两项属于企业级的特性，目前规划更多是在易用性和准确性方面
