### ISSUE TITLE
[Enhancement] 建议丰富标签的种类与创建方式

### ISSUE THREAD

**Issue by zhouhongyu888** [tencentmusic/supersonic#1712]
### Search before asking

- [X] I had searched in the [issues](https://github.com/tencentmusic/supersonic/issues?q=is%3Aissue) and found no similar issues.

### Description

目前的标签的创建方式比较单一，只能在创建模型的时候针对维度进行勾选创建，且标签中心也只是起到查看的作用
![image](https://github.com/user-attachments/assets/d035ce97-862d-47ae-83c5-55932cbac7cb)
![image](https://github.com/user-attachments/assets/22fe7099-9499-41f1-8ccb-8d20eee664fe)

### Solution

实际上标签不应该等同于维度。个人觉得标签统一在标签中心创建维护比较好，可以增加计算规则配置规则标签，甚至可以结合多维度或者指标创建标签

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by jerryjzhang** [comment]
你好，感谢反馈，确实跟我们的想法是契合的。后续将会把标签相关功能从语义层剥离，标签更多属于语义层之上的应用层，会单独做一个项目来迭代
