### ISSUE TITLE
[Bug] 语义sql翻译成执行sql出错：比如select sum(sum(xxx))

### ISSUE THREAD

**Issue by zhouzj1610** [tencentmusic/supersonic#1717]
### Search before asking

- [X] I had searched in the [issues](https://github.com/tencentmusic/supersonic/issues?q=is%3Aissue) and found no similar issues.

### Version

master分支

### What's Wrong?

语义sql正确，但翻译成执行sql后select和where条件都出错了，语义sql如下：
SELECT
  sum(特困人数),
  sum(低保人数),
  sum(低保边缘人数),
  sum(临时救助人数)
FROM
  xxx
WHERE
  街道名称 = 'xxxx'
  AND 创建日期 > date_sub ('2024-09-26', INTERVAL 7 day)

翻译成执行sql后，变成：
SELECT
  SUM(SUM(poor_num)),
  SUM(SUM(low_income_num)),
  SUM(SUM(low_marginal_num)),
  SUM(SUM(temp_rescue_num))
FROM
  xxxx
GROUP BY
  create_time,
  street_name
HAVING
  street_name = 'xxxx'
  AND create_time > date_sub ('2024-09-26', 7 *)
limit
  1000

### What You Expected?

翻译时能保持正确

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by lexluo09** [comment]
可以把大模型SQL、修正SQL、执行SQL都贴一下吗，界面上导出日志文件
