### ISSUE TITLE
[Enhancement] 【指标市场--指标探索】支持Postgresql数据库

### ISSUE THREAD

**Issue by flyingfish** [tencentmusic/supersonic#1726]
### Search before asking

- [X] I had searched in the [issues](https://github.com/tencentmusic/supersonic/issues?q=is%3Aissue) and found no similar issues.

### Description

【指标市场--指标探索】目前不支持Postgresql数据库的按周、按月粒度汇总数据

### Solution

希望适配Postgreqsql数据库，支持Postgresql数据库按周、按月粒度汇总

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by flyingfish** [comment]
以提交PR

**Comment by flyingfish** [comment]
已提交改功能完善的PR

**Comment by flyingfish** [comment]
https://github.com/tencentmusic/supersonic/pull/1727#issue-2552334499

**Comment by jerryjzhang** [comment]
谢谢！
