### ISSUE TITLE
[Feature] 【问答对话】增加【用户确认】步骤，可以在助理粒度配置开关

### ISSUE THREAD

**Issue by jerryjzhang** [tencentmusic/supersonic#1729]
### Search before asking

- [X] I had searched in the [issues](https://github.com/tencentmusic/supersonic/issues?q=is%3Aissue) and found no similar issues.

### Description

在schema mapping阶段如果映射到多个候选数据集或指标，当前是依赖一种启发性算法来选择最优解析，且通过TAB方式可切换其他解析。然而，通过TAB切换不太直观，容易被用户忽略，考虑在semantic execution之前提示用户来做确认。

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by zhouhongyu888** [comment]
是的，这个交互就会友好很多，同时有利于提高准确性
