### ISSUE TITLE
win :com.tencent.supersonic.StandaloneLauncher; .\supersonic-daemon.bat start都无法启动

### ISSUE THREAD

**Issue by 15185640400** [tencentmusic/supersonic#1733]
### Search before asking

- [X] I had searched in the [issues](https://github.com/tencentmusic/supersonic/issues?q=is%3Aissue) and found no similar issues.

### Version

最新版

### What's Wrong?

com.tencent.supersonic.StandaloneLauncher启动类在idea上启动报错：Error running 'StandaloneLauncher' Error running StandaloneLauncher. Command line is too long. Shorten the command line and rerun.
cmd窗口 .\supersonic-daemon.bat start失败

### What You Expected?

项目在win下跑起来

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by lexluo09** [comment]
请问报啥错呢，如果报spotless找不到java-formatter.xml问题，已经修复了

**Comment by 15271842237** [comment]
windows 源码打包 执行.\supersonic-daemon.bat start 黑窗口一闪而过 没有任何错误信息

**Comment by BigdataQIJI** [comment]
> windows 源码打包 执行.\supersonic-daemon.bat start 黑窗口一闪而过 没有任何错误信息

用powershell试试，以管理员身份打开
