### ISSUE TITLE
[Enhancement] 【语义查询】语义层执行异常时，将异常捕获并传递到导出日志

### ISSUE THREAD

**Issue by jerryjzhang** [tencentmusic/supersonic#1764]
### Search before asking

- [X] I had searched in the [issues](https://github.com/tencentmusic/supersonic/issues?q=is%3Aissue) and found no similar issues.

### Description

当前为了方便对具体的问答进行调试和问题定位，界面已经增加了【导出日志】按钮，可以将各阶段的输出统一记录与导出，但如果是语义层查询异常，导入日志缺乏记录，不便于集中定位问题。

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by lexluo09** [comment]
@jipeli 
https://github.com/tencentmusic/supersonic/pull/1778
发现一个问题这个pr，会将行列权限信息给淹没掉：
正常情况：
![image](https://github.com/user-attachments/assets/ab49cd66-431e-4c77-8f0e-6ce6af50d5b3)

异常情况：
<img width="1501" alt="image" src="https://github.com/user-attachments/assets/2007bf29-1661-44f4-92db-774fee86cf00">
<img width="1437" alt="image" src="https://github.com/user-attachments/assets/3f2d4f4f-16e4-4a90-9251-a7e781f1dc42">

**Comment by williamhuanliu** [comment]
https://github.com/tencentmusic/supersonic/pull/1803
