### ISSUE TITLE
[Feature] 【问答对话】单次问答支持导出数据

### ISSUE THREAD

**Issue by jerryjzhang** [tencentmusic/supersonic#1765]
### Search before asking

- [X] I had searched in the [issues](https://github.com/tencentmusic/supersonic/issues?q=is%3Aissue) and found no similar issues.

### Description

当前问答对话只能在线可视化呈现问询结果，应当支持对结果的文件导出

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by williamhuanliu** [comment]
https://github.com/tencentmusic/supersonic/pull/1803
