### ISSUE TITLE
[Bug] 最终查询语句的关联条件没有提前查询导致执行语法报错

### ISSUE THREAD

**Issue by zhouhongyu888** [tencentmusic/supersonic#1783]
### Search before asking

- [X] I had searched in the [issues](https://github.com/tencentmusic/supersonic/issues?q=is%3Aissue) and found no similar issues.

### Version

最新的docker镜像

### What's Wrong?

![img_v3_02fg_4b382ff3-29f6-45e6-bd97-52d3e5b9198g](https://github.com/user-attachments/assets/84c0ee29-172c-41d2-bbac-b77303f0674d)
![img_v3_02fg_ff9ee24b-43ef-46d8-88b6-592ecfb4792g](https://github.com/user-attachments/assets/44634049-c3f7-454a-859e-72d9fb3041c5)

### What You Expected?

对最终的物理sql增加语法的校验，确保关联属性字段包含在被查询的字段内

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by jipeli** [comment]
能导出日志看看吗？
