### ISSUE TITLE
[Enhancement] 是否支持mssql server数据连接支持？

### ISSUE THREAD

**Issue by 15074852943** [tencentmusic/supersonic#1797]
### Search before asking

- [X] I had searched in the [issues](https://github.com/tencentmusic/supersonic/issues?q=is%3Aissue) and found no similar issues.

### Description

目前系统似乎并不支持mssql server数据

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by lxwcodemonkey** [comment]
可以自己加一个jdbc 驱动试试

**Comment by 15074852943** [comment]
> 可以自己加一个jdbc 驱动试试

好的，已加

**Comment by aitting** [comment]
> > 可以自己加一个jdbc 驱动试试
> 
> 好的，已加

怎么添加，可以给一个步骤吗
