### ISSUE TITLE
问答界面增加对生成的SQL手动修改

### ISSUE THREAD

**Issue by ccckdi** [tencentmusic/supersonic#180]
可以考虑在问答界面，对返回的sql做修改后返给后端做double check后进行执行，这样对整体的使用上可能更灵活，相当于可以人工纠偏
![image](https://github.com/tencentmusic/supersonic/assets/56465277/1b5916c6-aed5-4d0b-a483-821ce849fab4)

**Comment by jerryjzhang** [comment]
感谢反馈，这个建议很好，我们来规划开发

**Comment by grantchenhuarong** [comment]
如果，使用者能够读懂、修改SQL的话，那应该用不上这个自然语言交互查询工具了，我想。
功能开发，需要定位受众，不一定啥feature都添加上去的。

**Comment by jerryjzhang** [comment]
> 如果，使用者能够读懂、修改SQL的话，那应该用不上这个自然语言交互查询工具了，我想。
> 功能开发，需要定位受众，不一定啥feature都添加上去的。

这里考虑的是可以增加角色，只有开发者角色的人才会看到生成的SQL和修改
