### ISSUE TITLE
[question] 日期功能

### ISSUE THREAD

**Issue by yanghp-max** [tencentmusic/supersonic#1806]
### Describe your question

对话问答生成的折线图那里有选择日期，近7天/30天/60天/90天，点击的时候数据没有任何变化，是怎么回事

**Comment by jerryjzhang** [comment]
这里是使用内置的DEMO，还是自定义的助理和语义模型？我们无法复现这个问题

**Comment by yanghp-max** [comment]
使用的自定义的，我看demo是使用的rule解析，这个没啥问题。我使用自定义助理和模型的时候是LLM解析，这个就不行

**Comment by jerryjzhang** [comment]
LLM解析会生成比较复杂的SQL，替换日期表达不太容易，建议不要修改
