### ISSUE TITLE
[Bug] 如果别名中有关键字 会导致无法生成物理SQL

### ISSUE THREAD

**Issue by dawsongzhao0523** [tencentmusic/supersonic#1809]
### Search before asking

- [X] I had searched in the [issues](https://github.com/tencentmusic/supersonic/issues?q=is%3Aissue) and found no similar issues.

### Version

0.9.8

### What's Wrong?

![image](https://github.com/user-attachments/assets/338e0113-6563-45f5-8d1b-0ecc22f515d4)

### What You Expected?

正确生成SQL

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by jerryjzhang** [comment]
最新版本应该不会有这个问题，会引导LLM生成别名时带下划线。

**Comment by dawsongzhao0523** [comment]
是在提示词修改的吗？我们用的自己的提示词，难怪。
