### ISSUE TITLE
[Bug] 插件/工具管理官方事例  意图解析失败

### ISSUE THREAD

**Issue by cutestyxy** [tencentmusic/supersonic#1822]
### Search before asking

- [X] I had searched in the [issues](https://github.com/tencentmusic/supersonic/issues?q=is%3Aissue) and found no similar issues.

### Version

0.9.6

### What's Wrong?

null

### What You Expected?

null

### Anything Else?

<img width="993" alt="image" src="https://github.com/user-attachments/assets/e48c8135-e883-4a99-9ab8-d5e61a4431f0">

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by lxwcodemonkey** [comment]
看日志应该是没识别到插件需要的参数值，可以看下你的插件配置吗

**Comment by cutestyxy** [comment]
> 看日志应该是没识别到插件需要的参数值，可以看下你的插件配置吗

官方超音数数据集只配置一个函数参数成功，配置多个函数参数报错；使用自己数据库建模报错
<img width="1093" alt="image" src="https://github.com/user-attachments/assets/5da5fe23-63c9-49a6-a89b-b3d91580a0e9">

**Comment by chenglongxie** [comment]
维度值设置，执行一下导入字典试试

**Comment by cutestyxy** [comment]
> 维度值设置，执行一下导入字典试试

是的 维度值没有设置
