### ISSUE TITLE
[Feature] 支持dify集成

### ISSUE THREAD

**Issue by dawsongzhao0523** [tencentmusic/supersonic#1827]
### Search before asking

- [X] I had searched in the [issues](https://github.com/tencentmusic/supersonic/issues?q=is%3Aissue) and found no similar issues.

### Description

Dify 是一个 LLMOps开源平台, 涵盖了大语言模型（如GPT系列）开发、部署、维护和优化的一整套实践和流程。可以大幅简化大模型应用的开发。
supersonic支持调用dify，可以获取以下收益：
- 使用dify托管模型，supersonic可以快速实现多模型效果对比验证。
- 使用dify的agent、workflow快速构建Agent原型，supersonic调用验证产品可行性。
- 使用dify的标注管理功能，可以快速缩减nl2sql的时间。
- 使用dify的知识库管理功能，可以在supersonic上做更多的知识管理和探索。

### Use case

模型托管和多模型效果对比
Workflow 编排Agent

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by dawsongzhao0523** [comment]
## 使用步骤
1）Dify构建自己的AI app，并获取APP Key
2）Supersonic Dify大模型设置配置
依次【大模型管理】->【创建大模型连接】->选择【接口协议DIFY】
<img width="1405" alt="image" src="https://github.com/user-attachments/assets/55d3a4cc-9dc0-43dc-b4ed-0bc26eb85cbf">

![image](https://github.com/user-attachments/assets/b4c73974-1c26-471a-8882-384074697d3a)

3）在Agent 中引用Dify 大模型连接

注意：
BaseUrl，必须填写 全路径，即https://xxx.xxx.xxx/v1/chat-messages
ModelName,随便填写，暂时没用；
目前只支持批量返回，流式接口还没适配。
如果您的dify做了用户名校验，请在源码中修改dify请求发起的username。

**Comment by dawsongzhao0523** [comment]
后续支持Workflow等能力

**Comment by 15074852943** [comment]
你好，按上面步骤配置dify的模型连接，创建助理后，进行问答，似乎不生效，
![image](https://github.com/user-attachments/assets/adf01f66-b7f2-4ab7-aea4-ebae72b944de)

接口返回如下：
![image](https://github.com/user-attachments/assets/da97a45b-f5b2-4dd8-a2af-cbfcb82bb851)

**Comment by dawsongzhao0523** [comment]
> 你好，按上面步骤配置dify的模型连接，创建助理后，进行问答，似乎不生效， ![image](https://private-user-images.githubusercontent.com/84566665/382660907-adf01f66-b7f2-4ab7-aea4-ebae72b944de.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3MDI1NTgsIm5iZiI6MTczMDcwMjI1OCwicGF0aCI6Ii84NDU2NjY2NS8zODI2NjA5MDctYWRmMDFmNjYtYjdmMi00YWI3LWFlYTQtZWJhZTcyYjk0NGRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA0VDA2MzczOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVkNzA0NjI4MmRjZGVjODNmMDJmNTI1NDdlYzQ4MTZmYzZlYjAyNjkxZmU2NTIxYjJkN2IxNmY4MDFlMDNiMGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.SXOBFUyZ7O_XXZADA0bmaVQM5eP_GcraPkHjStbaiu8)
> 
> 接口返回如下： ![image](https://private-user-images.githubusercontent.com/84566665/382660569-da97a45b-f5b2-4dd8-a2af-cbfcb82bb851.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3MDI1NTgsIm5iZiI6MTczMDcwMjI1OCwicGF0aCI6Ii84NDU2NjY2NS8zODI2NjA1NjktZGE5N2E0NWItZjViMi00ZGQ4LWEyYWYtY2JmY2I4MmJiODUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA0VDA2MzczOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRlNGY4NDg0NWMwMmI4ZDIxNTVlYzljMTRiMmI3ODY2Y2NkNzA4ODA0M2YzNTk4ZTlmNmY0ZTBkMjRlYjJlYmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.luMeFIDzaiL-dFV82Ww6iFUqbD81CRaQrljToIuN1as)

1、看一下dify是否有收到请求；2、看一下应用日志

**Comment by 15074852943** [comment]
> > 你好，按上面步骤配置dify的模型连接，创建助理后，进行问答，似乎不生效， ![image](https://private-user-images.githubusercontent.com/84566665/382660907-adf01f66-b7f2-4ab7-aea4-ebae72b944de.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3MDI1NTgsIm5iZiI6MTczMDcwMjI1OCwicGF0aCI6Ii84NDU2NjY2NS8zODI2NjA5MDctYWRmMDFmNjYtYjdmMi00YWI3LWFlYTQtZWJhZTcyYjk0NGRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA0VDA2MzczOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVkNzA0NjI4MmRjZGVjODNmMDJmNTI1NDdlYzQ4MTZmYzZlYjAyNjkxZmU2NTIxYjJkN2IxNmY4MDFlMDNiMGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.SXOBFUyZ7O_XXZADA0bmaVQM5eP_GcraPkHjStbaiu8)
> > 接口返回如下： ![image](https://private-user-images.githubusercontent.com/84566665/382660569-da97a45b-f5b2-4dd8-a2af-cbfcb82bb851.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3MDI1NTgsIm5iZiI6MTczMDcwMjI1OCwicGF0aCI6Ii84NDU2NjY2NS8zODI2NjA1NjktZGE5N2E0NWItZjViMi00ZGQ4LWEyYWYtY2JmY2I4MmJiODUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA0VDA2MzczOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRlNGY4NDg0NWMwMmI4ZDIxNTVlYzljMTRiMmI3ODY2Y2NkNzA4ODA0M2YzNTk4ZTlmNmY0ZTBkMjRlYjJlYmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.luMeFIDzaiL-dFV82Ww6iFUqbD81CRaQrljToIuN1as)
> 
> 1、看一下dify是否有收到请求；2、看一下应用日志

你好，dify未收到请求，但是配置好后测试连接成功：
![image](https://github.com/user-attachments/assets/9824db19-6964-4c09-895f-f14c0fb5f245)

使用助理问答时，没有应用日志
![image](https://github.com/user-attachments/assets/e57c6b22-167f-41eb-bf5e-97e96536b3c8)

**Comment by ShouyuanQ** [comment]
在助理配置里，似乎不能配置数据集，否则会意图识别失败。（类似“闲聊”不能配置数据集，否则会失败）
是否有可能在supersonic的agent里同时保留text2sql，以及闲聊（调dify）的能力，或者是通过插件（调dify）的能力。
这样单个agent在text2sql的专业基础上，对其他问题有比较灵活的处理和拓展。
