### ISSUE TITLE
[Feature] 【问答对话】增加对单次问答结果的追问

### ISSUE THREAD

**Issue by jerryjzhang** [tencentmusic/supersonic#1832]
### Search before asking

- [X] I had searched in the [issues](https://github.com/tencentmusic/supersonic/issues?q=is%3Aissue) and found no similar issues.

### Description

目前实现追问是通过多轮对话的方式来实现，但是会遇到两方面的挑战：
1、结合历史对话和本轮对话的问题改写，改写后的问题可能会出现信息丢失或者失真；
2、需要重新发起数据查询，不能对上轮结果直接进行提炼解读。
考虑在问答结果的末尾增加【追问】按钮，可以对本次数据结果直接进行提问和分析

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by fenglaijun** [comment]
你好，请问这个feature是无法支持吗？还是后续会支持？
