### ISSUE TITLE
[question] 0.9.8版本的镜像是不是有问题

### ISSUE THREAD

**Issue by rongruosong** [tencentmusic/supersonic#1879]
### Describe your question

web界面有0.9.6的无变化
![image](https://github.com/user-attachments/assets/0e2691a7-4111-436e-90d1-fb6fffcc1821)

**Comment by lexluo09** [comment]
执行一下：docker compose  down -v，清除一下以前版本的lib、webapp
1、docker compose  down -v
2、docker compose  up -d

**Comment by lexluo09** [comment]
<img width="1510" alt="image" src="https://github.com/user-attachments/assets/5393524d-ad61-440a-ad08-dd0683dd8b1f">
操作完成后就是正常的了

**Comment by rongruosong** [comment]
> 执行一下：docker compose down -v，清除一下以前版本的lib、webapp 1、docker compose down -v 2、docker compose up -d

![image](https://github.com/user-attachments/assets/7b7ec14d-dfca-4ed2-b9e4-ac8a77df1bdf)
docker-compose -p supersonic up -d,启动后直接打不开了

**Comment by rongruosong** [comment]
可以了，感谢
