### ISSUE TITLE
[question] 指标探索-维度筛选无效果

### ISSUE THREAD

**Issue by rongruosong** [tencentmusic/supersonic#1888]
### Describe your question

![image](https://github.com/user-attachments/assets/6ea73b75-3393-4122-897c-1c157b00b9de)
指标探索这里的维度筛选目前是不起作用吗

**Comment by lexluo09** [comment]
是生效的，需要点击一下+添加进去


<img width="860" alt="image" src="https://github.com/user-attachments/assets/aaf11988-1607-428e-ab26-ce391f03732b">

**Comment by rongruosong** [comment]
感谢
