### ISSUE TITLE
[question] 本地IDE无法启动

### ISSUE THREAD

**Issue by chenchenchen7** [tencentmusic/supersonic#1890]
### Describe your question

Mac Intel芯片电脑，使用最新release代码，StandaloneLauncher启动后卡在下面两行代码，不继续启动容器了。

16:34:00 [scheduling-1] INFO  c.t.s.h.c.k.helper.HanlpHelper 108 - Custom dictionary has been reloaded in 27 milliseconds
16:34:00 [scheduling-1] INFO  c.t.s.h.s.s.impl.DictWordService 51 - Dictionary has been regularly reloaded in 71 milliseconds

### Provide any additional context or information

![image](https://github.com/user-attachments/assets/91433b41-f53e-4e44-b991-f266cf67876a)
直接启动项目，没有初始化db

### Your environment

mac os Intel Core i7

supersonic-0.9.8

**Comment by chenchenchen7** [comment]
node版本低，第一次打包时候失败了。升级后再打包就可以访问了，其实应用已经起来了，只是没拉到前端资源

**Comment by wwfra** [comment]
楼主您好，请问解决了吗？我的也是没前端
