### ISSUE TITLE
[Bug] 删除已存在的助手后，日志会不停地刷： [scheduling-1] WARN  c.t.s.c.s.memory.MemoryReviewTask 73 - Agent id 4 not found or memory review disabled

### ISSUE THREAD

**Issue by 15074852943** [tencentmusic/supersonic#1891]
### Search before asking

- [X] I had searched in the [issues](https://github.com/tencentmusic/supersonic/issues?q=is%3Aissue) and found no similar issues.

### Version

0.9.8

### What's Wrong?

删除助手后，后台日志无线刷：
![image](https://github.com/user-attachments/assets/06c18774-6124-4d03-ad1c-2a9169fb7c86)

### What You Expected?

如何解决这种问题

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by chenglongxie** [comment]
s2_chat_memory表删除一下agent_id为日志中显示的值的数据试试

**Comment by lxwcodemonkey** [comment]
应该是当次定时任务在执行的过程中会去刷，后续的定时任务执行的时候应该就不会刷了，因为会重新加载助理列表

**Comment by 15074852943** [comment]
> 应该是当次定时任务在执行的过程中会去刷，后续的定时任务执行的时候应该就不会刷了，因为会重新加载助理列表

谢谢，已经可以了
