### ISSUE TITLE
[Bug] 获取术语逻辑里有死循环报错

### ISSUE THREAD

**Issue by Alita-Z** [tencentmusic/supersonic#1894]
### Search before asking

- [X] I had searched in the [issues](https://github.com/tencentmusic/supersonic/issues?q=is%3Aissue) and found no similar issues.

### Version

0.9.8

### What's Wrong?

配置术语后，运行到该文件代码行时死循环异常：com/tencent/supersonic/headless/chat/mapper/TermDescMapper.java:29

### What You Expected?

修复死循环bug

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by lexluo09** [comment]
可以将配置术语信息提供一下吗，我们复现一下
