### ISSUE TITLE
[question] springboot3是有计划支持

### ISSUE THREAD

**Issue by mislayming** [tencentmusic/supersonic#1904]
### Describe your question

打算集成服务端到应用里，但是现在都是springboot3的版本，但不想搞多个微服务，所以集成上会冲突。。。

**Comment by jerryjzhang** [comment]
下个版本我们来验证下spring 3.0

**Comment by mislayming** [comment]
> 下个版本我们来验证下spring 3.0

我拉了个分支修改了一个版本，已经和我自己的服务集成了，怎么给你合并回来呢？

**Comment by jerryjzhang** [comment]
提交PR 就好了
















在 2024-12-06 13:48:37，"mislayming" ***@***.***> 写道：

下个版本我们来验证下spring 3.0

我拉了个分支修改了一个版本，已经和我自己的服务集成了，怎么给你合并回来呢？

**Comment by mislayming** [comment]
SpringBoot3升级 #1947
