### ISSUE TITLE
[question] password encrypt error

### ISSUE THREAD

**Issue by HongFive** [tencentmusic/supersonic#1905]
### Describe your question

 Pulling the latest docker image to deploy, the password for admin is not 123456 nor admin, what is the default password?

**Comment by lxwcodemonkey** [comment]
I seem to be able to login using the latest image. The account number is admin and the password is 123456. You can try again. If you have any questions, feel free to contact us.

**Comment by 1586957845** [comment]
Java's default encryption policy imposes a limit on key sizes (e.g., a maximum of 128 bits for AES). Exceeding this limit will trigger this exception. Upgrading your JDK version can resolve the issue.
