### ISSUE TITLE
[Bug] MySQL数据库的版本为5.7，生成的SQL中有版本不支持的with语法

### ISSUE THREAD

**Issue by sudaflower** [tencentmusic/supersonic#1915]
### Search before asking

- [X] I had searched in the [issues](https://github.com/tencentmusic/supersonic/issues?q=is%3Aissue) and found no similar issues.

### Version

0.9.8

### What's Wrong?

生成的SQL中有MySQL版本不支持的SQL语法： 
![图片](https://github.com/user-attachments/assets/7110d960-cc75-4885-abe5-bae9df2f9597)

### What You Expected?

生成符合版本的SQL语法

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by jerryjzhang** [comment]
已经修复，只有在mysql 8.0 版本以上才会支持with
