### ISSUE TITLE
[question] 能不能出一篇文档，详细讲讲super sonic中的Translator层是怎么实现的

### ISSUE THREAD

**Issue by blue-vision0** [tencentmusic/supersonic#1931]
### Describe your question

能不能出一篇文档，详细讲讲super sonic中的Translator层是怎么实现的。感觉这部分挺重要的，但是在文档中一笔带过了。

**Comment by jerryjzhang** [comment]
你好，这个在规划中，但是目前主要精力还是迭代特性和优化，可以在群里跟详细阅读代码的同伴们去交流
