### ISSUE TITLE
[question] 模型上新建单个带过滤条件的指标，请问怎么实现

### ISSUE THREAD

**Issue by ShouyuanQ** [tencentmusic/supersonic#1939]
### Describe your question

0.9.8版本，在原有数据模型上，新建指标时如何加上过滤条件？
具体如图，例如新指标的表达式，按照A+B where A is null，这样的写法是可以的吗。
配置可以成功，但问答时并没有生效

### Provide any additional context or information

![20241202-172929](https://github.com/user-attachments/assets/d66afe3b-8cb1-4538-8d3d-357f3da0246b)

**Comment by ShouyuanQ** [comment]
![20241204](https://github.com/user-attachments/assets/acbcc115-f15e-4b34-9de5-36092dc0c817)
暂时按官方文档处理了，探索更多用法~~

**Comment by 15074852943** [comment]
怎么实现的？

**Comment by ShouyuanQ** [comment]
限定条件里，写字段名过滤，例如 column like '%XX%' ,不要带where。表达式保持原样的度量名称就行（例如s2_pv_uv_statis_pv）


> 怎么实现的？
