### ISSUE TITLE
[Bug] data-mysql-demo.sql 初始化脚本问题

### ISSUE THREAD

**Issue by zhangqian-code** [tencentmusic/supersonic#1940]
### Search before asking

- [X] I had searched in the [issues](https://github.com/tencentmusic/supersonic/issues?q=is%3Aissue) and found no similar issues.

### Version

![QQ_1733205264071](https://github.com/user-attachments/assets/c22a5760-8831-4c04-838d-0e1f8b983636)

### What's Wrong?

not supporter

### What You Expected?

correct

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by supersonicbi** [comment]
你好，最新代码已经修复
