### ISSUE TITLE
[Bug] - docker-compose部署启动时db_init容器找不到脚本

### ISSUE THREAD

**Issue by MrXionGe** [tencentmusic/supersonic#1941]
### Search before asking

- [X] I had searched in the [issues](https://github.com/tencentmusic/supersonic/issues?q=is%3Aissue) and found no similar issues.

### Version

0.9.8

### What's Wrong?

启动时，db_init容器报错，找不到sql脚本
sh: 3: cannot open /usr/src/app/supersonic-standalone-0.9.8/conf/db/schema-mysql-demo.sql: No such file
如图：
![image](https://github.com/user-attachments/assets/c2c2f203-8068-49ed-b060-b87fe97e4ad7)

### What You Expected?

通过查看Dockerfile和项目文件可知，镜像打包的时候，没有包含demo名称的sql脚本。
删除docker-compose.yml中的这两行，就解决了问题，如图：
![image](https://github.com/user-attachments/assets/4ebce906-e504-41b5-a91b-77bf23369979)

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by iCodingMax** [comment]
之前也遇到了这个问题，检查是Docker启动之后，启动SQL初始化脚本找不到相关路径，可以把standalone版本固定为0.9.8试一下：
![image](https://github.com/user-attachments/assets/82e2bd14-e1d9-4354-87a6-a75e40c5f97b)

**Comment by snowdream** [comment]
这代码都不经过测试的吗？😅



```
root@vultr:~/docker/supersonic# docker compose up -d
[+] Running 41/4
 ✔ chroma Pulled                                                                                                                                                             53.4s 
 ✔ mysql Pulled                                                                                                                                                              52.4s 
 ✔ db_init Pulled                                                                                                                                                            65.9s 
 ✔ supersonic_standalone Pulled                                                                                                                                              65.9s 
[+] Running 8/8
 ✔ Network supersonic_supersonic_network  Created                                                                                                                             0.2s 
 ✔ Volume "supersonic_supersonic_data"    Created                                                                                                                             0.0s 
 ✔ Volume "supersonic_chroma_data"        Created                                                                                                                             0.0s 
 ✔ Volume "supersonic_mysql_data"         Created                                                                                                                             0.0s 
 ✔ Container supersonic_chroma            Healthy                                                                                                                            26.6s 
 ✔ Container supersonic_mysql             Healthy                                                                                                                            26.0s 
 ✘ Container supersonic_db_init           service "db_init" didn't complete successfully: exit 2                                                                             41.5s 
 ✔ Container supersonic_standalone        Created                                                                                                                             2.3s 
service "db_init" didn't complete successfully: exit 2

```


<img width="1089" alt="image" src="https://github.com/user-attachments/assets/f2a05327-8a13-454b-8191-7e0c5c742860">

**Comment by jerryjzhang** [comment]
我这边测试镜像是没问题的

**Comment by bbslab** [comment]
遇到了一样的问题，依赖死循环了奥

**Comment by snowdream** [comment]
建议切换到 tag：

https://github.com/tencentmusic/supersonic/releases/tag/v0.9.8

再构建

**Comment by Jenewang** [comment]
感觉容器参数用的postgresql，但数据库初始化用的还是mysql，就是手工初始化数据后应用程序连接还是用mysql的驱动去连接造成错误

**Comment by collins2005** [comment]
root:/data>docker logs supersonic_db_init
sh: 2: psql: not found
sh: 4: cannot open /usr/src/app/supersonic-standalone-latest/conf/db/schema-postgres.sql: No such file
sh: 5: cannot open /usr/src/app/supersonic-standalone-latest/conf/db/schema-postgres-demo.sql: No such file
sh: 6: cannot open /usr/src/app/supersonic-standalone-latest/conf/db/data-postgres.sql: No such file
sh: 7: cannot open /usr/src/app/supersonic-standalone-latest/conf/db/data-postgres-demo.sql: No such file

**Comment by jerryjzhang** [comment]
这里主要是用了master 还没有发布的docker-compose.xml，但是镜像还没有更新，请大家使用老版本的docker-compose.xml

**Comment by jerryjzhang** [comment]
supersonicbi/supersonic:latest 已经指向了最新的supersonicbi/supersonic:0.9.10-SNAPSHOT，跟master 代码是保持同步的了

**Comment by jerryjzhang** [comment]
docker-compose.xml 文件也需要更新为master 分支最新版
