### ISSUE TITLE
[question] 为什么要升级到jdk17

### ISSUE THREAD

**Issue by BrianApple** [tencentmusic/supersonic#1962]
### Describe your question

好奇为什么要升级到jdk17，而且springboot版本升级到了3.x，与目前官方文档中的建议jdk11不兼容，我看了下源码，主要是一些参数校验使用了springboot3.x中的jakarta工具包，其他变化并不是特别明显，是有什么特别的考虑嘛

**Comment by supersonicbi** [comment]
这个是有外部contributor贡献的，还在master 没有发布，下个版本release 会修改文档

**Comment by jerryjzhang** [comment]
这个是有外部contributor贡献的，还在master 没有发布，下个版本release 会修改文档

**Comment by BrianApple** [comment]
好的，感谢答疑，不过个人建议：如果升级到17后，从性能或功能上没有带来比较明显收益的情况下，jdk版本建议继续保持向下兼容到1.8～   如果确认升级到17的话，文档建议同步及时更新，感谢～

**Comment by mislayming** [comment]
感觉兼容有些难，
站在企业级应用角度看，springboot2已经没人维护了。。。。所以必须升级
现在很多的新的第三方包也不支持1.8了，老的包又有很多安全问题。。。一升级又要求要高版本jdk
最后就是S2的License，不用他的前端可以自由使用嘛，所以肯定有大部分集成场景，现在的企业项目基于前两点都是boot3了，冲突啊

**Comment by BrianApple** [comment]
现在很多公司还是以1.8为主，迁移难度还是有点大～  新项目还好，老项目做集成还是比较麻烦 哈哈
