### ISSUE TITLE
[Bug] Network中所有前端路由资源请求均报404错误

### ISSUE THREAD

**Issue by yxm-coding** [tencentmusic/supersonic#1982]
### SuperSonic version

0.9.8

### Your organization

个人

### Description

项目各个页面能正常访问，但是打开控制台发现所有前端路由资源请求均报404错误
![bug](https://github.com/user-attachments/assets/2433ada0-a7c3-4722-989d-5065ff9a768d)

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by jerryjzhang** [comment]
感谢
