### ISSUE TITLE
Syntax error of run script bin/start-standalone.sh

### ISSUE THREAD

**Issue by wenguixuan** [tencentmusic/supersonic#27]
/home/guixuanwen/projects/0.6-SNAPSHOT/../runtime/supersonic-standalone/bin/service.sh: 6: source: not found
/home/guixuanwen/projects/0.6-SNAPSHOT/../runtime/supersonic-standalone/bin/service.sh: 10: Syntax error: "(" unexpected
/home/guixuanwen/projects/0.6-SNAPSHOT/../runtime/supersonic-standalone/llm/bin/service.sh: 5: source: not found
/home/guixuanwen/projects/0.6-SNAPSHOT/../runtime/supersonic-standalone/llm/bin/service.sh: 9: Syntax error: "(" unexpected

**Comment by CreationLee** [comment]
same issue

**Comment by lexluo09** [comment]
Thank you for your suggestion. It could be a linux system version issue, and I will fix this problem immediately.

**Comment by lexluo09** [comment]
@wenguixuan  @CreationLee 
I have fixed this issue. We have upgraded to the latest release version, which includes many new features. Feel free to try it out. Thank you.

https://github.com/tencentmusic/supersonic/releases/tag/v0.7.2
