### ISSUE TITLE
支持对每一个Model单独定义exemplars

### ISSUE THREAD

**Issue by jerryjzhang** [tencentmusic/supersonic#322]
### 背景
当前，supersonic会在schema mapping阶段根据一定规则从候选里选择一个最匹配的model，再调用LLM来Text-to-SQL。调用LLM可以有few-shot和zero-shot两种方式，实验表明few-shot相比zero-shot在很多场景下能带来更好效果，因而，supersonic内置sql_exampler.py文件来自定义few-shot的示例。然而，few-shot示例应当更加精细化，可以针对每个model来单独定义，理论上可以减少对LLM的干扰。

**Comment by codescracker** [comment]
@jerryjzhang @lexluo09 好的。后续会增加一个字段，和每一个model一一对应。用户可以选择model对应的例子的范围，扩增例子的针对性。

**Comment by codescracker** [comment]
https://github.com/tencentmusic/supersonic/pull/342

**Comment by codescracker** [comment]
> @jerryjzhang @lexluo09 好的。后续会增加一个字段，和每一个model一一对应。用户可以选择model对应的例子的范围，扩增例子的针对性。

https://github.com/tencentmusic/supersonic/pull/342
