### ISSUE TITLE
要如何进行数据持久化

### ISSUE THREAD

**Issue by tianhe1986** [tencentmusic/supersonic#329]
请教一下，要如何配置，才能让新创建的数据能够持久化呢。

现在是stop再start，新创建的数据库连接，模型就全部没了，有没有办法让它们写入本地文件/数据库，下次启动时还能继续用呢。

**Comment by lexluo09** [comment]
1、目前默认方式是采用H2数据库，为了演示方便；重启后数据恢复使用；
2、可以修改application-local.yaml文件中的配置，将h2数据库相关配置修改为自己搭建的mysql;

**Comment by tianhe1986** [comment]
非常感谢指导哈，我把H2数据库的地址改成了本地文件，能够正常持久化了。
