### ISSUE TITLE
No module named 'few_shot_example.sql_exampler'

### ISSUE THREAD

**Issue by gj-zhang** [tencentmusic/supersonic#36]
few_shot_example dir is empty

**Comment by lexluo09** [comment]
Thank you for your issues. we will fix this problem immediately.

**Comment by lexluo09** [comment]
we have fixed this issue. Feel free to try it out. Thank you.
https://github.com/tencentmusic/supersonic/pull/38

**Comment by lexluo09** [comment]
@gj-zhang you can try again. I will close this issue.
