### ISSUE TITLE
Python服务用Java工程重写，默认为Java实现

### ISSUE THREAD

**Issue by jerryjzhang** [tencentmusic/supersonic#396]
当前python服务主要用于跟LLM和Vector数据库的交互，功能上不复杂，但是会带来额外的环境依赖、进程通信和服务维护的代价，考虑用Java工程完全替代

**Comment by bowenliang123** [comment]
当前Python主要提供了Langchain的封装，并且协调管理了对Vector数据库、LLM调用等关键大模型场景应用能力。
Langchain已经成为事实上的唯一LLM场景开发框架，一方面横向上充分跟进所有热门的上游模型和服务的外观变化，这会大大保留我们对不同服务的适配潜能，另一方面纵向上有效解耦合抽取了关键的module，能够有效体现最新LLM能力和入口。

以Java组件（langchain-java、langchain4j）去替代，将会面临对上游服务的版本跟踪和不一致，永远处于下游，且使用广度、文档上完善程度不及预期，得不偿失。大量新型的组件甚至不会提供任何Java的版本供对接，而实际我们投产由于私有化部署、异构共享等的情况，还是需要做一定的适配，保留这种潜力将会至关重要。

当前Python服务的主要问题集中于工程化，从依赖、构建打包、生命周期、运行时启动方面，更多是在编码和设计模式上的缺失，同时由于自动化CI验证的空缺，导致Python服务与Java服务的配合不佳。

就我看来，这些都是可以通过测试驱动、设计模式上的方式去满足的。尤其是Langchain本身还提供了Fake LLM类似的用于简单测试的模拟能力，我们应该把重点放在以现在架构的组合模式，进一步深化工程实践。


就目前所见，Python Langchain仍然是拥抱整个LLM应用时代的关键能力。

**Comment by jerryjzhang** [comment]
> 当前Python主要提供了Langchain的封装，并且协调管理了对Vector数据库、LLM调用等关键大模型场景应用能力。 Langchain已经成为事实上的唯一LLM场景开发框架，一方面横向上充分跟进所有热门的上游模型和服务的外观变化，这会大大保留我们对不同服务的适配潜能，另一方面纵向上有效解耦合抽取了关键的module，能够有效体现最新LLM能力和入口。
> 
> 以Java组件（langchain-java、langchain4j）去替代，将会面临对上游服务的版本跟踪和不一致，永远处于下游，且使用广度、文档上完善程度不及预期，得不偿失。大量新型的组件甚至不会提供任何Java的版本供对接，而实际我们投产由于私有化部署、异构共享等的情况，还是需要做一定的适配，保留这种潜力将会至关重要。
> 
> 当前Python服务的主要问题集中于工程化，从依赖、构建打包、生命周期、运行时启动方面，更多是在编码和设计模式上的缺失，同时由于自动化CI验证的空缺，导致Python服务与Java服务的配合不佳。
> 
> 就我看来，这些都是可以通过测试驱动、设计模式上的方式去满足的。尤其是Langchain本身还提供了Fake LLM类似的用于简单测试的模拟能力，我们应该把重点放在以现在架构的组合模式，进一步深化工程实践。
> 
> 就目前所见，Python Langchain仍然是拥抱整个LLM应用时代的关键能力。

感谢bowen的建议，已经就该问题私下沟通。简单总结下，默认会用Java来替代Python服务以简化开发维护代价，但是会保留对接Python服务的接口实现，以防后续需要采用LangChain生态能力的诉求。
