### ISSUE TITLE
DatabaseReq  建议是使用jdbc url  替代host 和 port

### ISSUE THREAD

**Issue by witkeyshare** [tencentmusic/supersonic#462]
当前jdbc url 目前是拼接的，实际上需要增加额外的链接参数是实现特定的目的，拼接的无法满足需求。

比如我的 mysql链接需要配置 &useSSL=false，我就要改代码

    public String getUrl() {
        if (type.equalsIgnoreCase(DataTypeEnum.H2.getFeature())) {
            return url;
        }
        String databaseUrl = database;
        if (StringUtils.isBlank(databaseUrl)) {
            databaseUrl = "";
        } else {
            databaseUrl = "/" + database;
        }
        if (type.equalsIgnoreCase(DataTypeEnum.MYSQL.getFeature())) {
           return String.format("jdbc:%s://%s:%s%s?sessionVariables=sql_mode='IGNORE_SPACE'&allowMultiQueries=true&%s",
                    type, host, port, databaseUrl, "useSSL=false");
        }
        return String.format("jdbc:%s://%s:%s%s", type, host, port, databaseUrl);
    }

**Comment by lxwcodemonkey** [comment]
我们优化一下 可以既提供URL的方式 也提供直接填写IP和端口进行拼接的方式
