### ISSUE TITLE
关于docker镜像，建议发布两个镜像，java后端、react前端，

### ISSUE THREAD

**Issue by witkeyshare** [tencentmusic/supersonic#463]
关于docker镜像，建议发布两个镜像，java后端、react前端，python大模型如果后续继续保留的话，把本地的mysql镜像也可以考虑进去。

使用docker-compose拉去相关的镜像，降低试用、及测试成本

**Comment by jerryjzhang** [comment]
收到建议，docker镜像一直在规划中，不过有很多特性还在排队中，开发人力有限只能延后一些

**Comment by jerryjzhang** [comment]
规划在0.9.4版本上线
