### ISSUE TITLE
推荐bug

### ISSUE THREAD

**Issue by huangtianan** [tencentmusic/supersonic#47]
置了指标不可见，但是推荐出来了
<img width="851" alt="076fcc80d597d4f8f42cb0e8588a3de" src="https://github.com/tencentmusic/supersonic/assets/19199077/cb24ed08-9685-4e4d-aa90-ac10dc4b987b">
<img width="753" alt="a174c2962c3e718e4a6adba5a487f74" src="https://github.com/tencentmusic/supersonic/assets/19199077/9ec5a5e3-9985-4c1a-ac8b-90eabf2eaf64">

**Comment by lexluo09** [comment]
Thank you for your issues. we will fix this problem immediately.

**Comment by lexluo09** [comment]
We have fixed this case. https://github.com/tencentmusic/supersonic/pull/72
