### ISSUE TITLE
指标解读保存后前端返显数字

### ISSUE THREAD

**Issue by ccckdi** [tencentmusic/supersonic#55]
指标解读保存后前端返显数字，在问答时好像不生效
![image](https://github.com/tencentmusic/supersonic/assets/56465277/f8a73424-06fb-4d8a-af36-9ca121dd7760)

**Comment by williamhuanliu** [comment]
指标值回显问题已修复，已提交到master分支，可以试下看 https://github.com/tencentmusic/supersonic/pull/56

**Comment by lxwcodemonkey** [comment]
问答不生效的情况会不会有可能是没有配置LLM呢？有具体的截图吗

**Comment by ccckdi** [comment]
启动时报错了
![20230905-143224](https://github.com/tencentmusic/supersonic/assets/56465277/b3a6b39b-9713-4b59-a868-d3784e66b275)

**Comment by lexluo09** [comment]
这个是llm python服务启动报错，需要安装必要的python版本和pip版本，这个报错不影响其他的使用发自我的 iPhone在 2023年9月5日，14:34，Chx ***@***.***> 写道：﻿
启动时报错了

**Comment by lexluo09** [comment]
> 启动时报错了 ![20230905-143224](https://user-images.githubusercontent.com/56465277/265606479-b3a6b39b-9713-4b59-a868-d3784e66b275.png)
可以在这里配置您的pip、python路径
<img width="735" alt="image" src="https://github.com/tencentmusic/supersonic/assets/39718951/2c0de098-28a2-4e77-9db0-3f549d73a434">
