### ISSUE TITLE
Headless语义模型字段的日期格式支持年、周、季度

### ISSUE THREAD

**Issue by lexluo09** [tencentmusic/supersonic#616]
目前这个日期是必须，暂时不能支持年度年、周、季度等日期格式；
<img width="594" alt="image" src="https://github.com/tencentmusic/supersonic/assets/39718951/f16f0686-d1b7-4b77-87ee-ed3ec69cf971">

**Comment by JourneytoNewland** [comment]
关键是筛选条件时间条件是否能变成月控件。月指标存的是月份，现在都是日期。设值YYYYMM，但看解析传的就是 YYYY-MM。

数据库：GP

![image](https://github.com/tencentmusic/supersonic/assets/44330206/bb00e879-a080-4491-ace7-5f0354da08f9)
![image](https://github.com/tencentmusic/supersonic/assets/44330206/8a43ed65-8348-4800-9b14-be063b6617d0)
