### ISSUE TITLE
支持在对话中显式指定同环比分析

### ISSUE THREAD

**Issue by cuzlab** [tencentmusic/supersonic#723]
目前仅支持按照输入条件进行日环比、周环比计算，且仅对单个数值。
同环比作为数据分析领域常见的分析类别，支持显式指定同环比，可以扩大超音速的适用范围
e.g. 
![同环比](https://github.com/tencentmusic/supersonic/assets/46290024/b84fbf22-ef32-4712-86b5-14cfe984fc6e)

**Comment by jerryjzhang** [comment]
感谢反馈，这个需求我们加入到迭代计划中去
