### ISSUE TITLE
前端数据展示不全，编辑之后数据没有刷新

### ISSUE THREAD

**Issue by yynied** [tencentmusic/supersonic#757]
1.在模型的指标页面编辑指标之后，页面没有刷新数据，点击还是旧数据，需要重调接口刷新。
2.问答对话页面左边的智能助理过多之后无法显示最新增加的智能助理，需要支持下滑展示更多智能助理

**Comment by sevenliu1896** [comment]
智能助理问题合并至 #981 

> 1.在模型的指标页面编辑指标之后，页面没有刷新数据，点击还是旧数据，需要重调接口刷新。
该问题如果更新版本后仍然存在，请创建新的issue并提供相应操作截图
@yynied
