### ISSUE TITLE
如何配置RATIO_ROLL、RATIO_OVER？

### ISSUE THREAD

**Issue by jersy** [tencentmusic/supersonic#827]
在前台页面上只能看到截图里的下拉框， TOPN，PERCENTILE，RATIO_ROLL，RATIO_OVER要怎么配置？

<img width="1245" alt="image" src="https://github.com/tencentmusic/supersonic/assets/1180793/e903f4bb-18cc-40f7-ad28-0c55a05da8f2">

<img width="528" alt="image" src="https://github.com/tencentmusic/supersonic/assets/1180793/4a7283f5-49b0-4c45-8733-fa6e69f77465">

**Comment by lexluo09** [comment]
您好，感谢您的提问，暂时还不支持配置RATIO_ROLL、RATIO_OVER、TOPN的聚合方式；
