### ISSUE TITLE
是否考虑支持增删改功能？

### ISSUE THREAD

**Issue by JourneytoNewland** [tencentmusic/supersonic#896]
目前看主要是自助取数用，是否有对数据库增删改操作的演进

**Comment by jerryjzhang** [comment]
你好，是指通过自然语言去执行增删改操作吗？

**Comment by JourneytoNewland** [comment]
是的。类DB-GPT自然语言对数据库操作。

**Comment by jerryjzhang** [comment]
暂时不会支持，目前的定位是BI分析平台，不是做数据库操作的Ops平台

**Comment by dawsongzhao0523** [comment]
建议使用类似nocodb、teable、apitable这种类似的协同在线表格做数据录入和处理，直接使用supersonic对接这些表格底层的数据库表。
