### ISSUE TITLE
【语义建模】支持自动从库表字段获取注释来填充度量/维度中文名称

### ISSUE THREAD

**Issue by mxli441** [tencentmusic/supersonic#933]
I have 185 columns  in my database and each column has a chinese  comment ,the database type is mysql,when I build the semantic model ,I need to input the chinese comments of the columns one by one ,it watsed lots of  my time .
![1713925322230](https://github.com/tencentmusic/supersonic/assets/70192192/0171490b-508c-447c-adb2-265bcc662a69)
![1713925663044](https://github.com/tencentmusic/supersonic/assets/70192192/11f449dc-e71d-4c5b-9d44-d00dde881c27)

**Comment by jerryjzhang** [comment]
@mxli441 did you fill comments when creating the MySQL tables?

**Comment by mxli441** [comment]
YES
