### ISSUE TITLE
Headless支持智能建模

### ISSUE THREAD

**Issue by lexluo09** [tencentmusic/supersonic#946]
背景：现阶段使用问答或其他应用时，需对数据进行语义建模；但语义建模效率降低，考虑智能化、自动化进行建模；提升建模整体效率

1、基于连接的库表信息，自动化、智能化创建纬度、指标
2、自动化创建指标、纬度别名、描述等；
3、自动化创建各模型之间的关联关系；

**Comment by rabintang** [comment]
今天看到快手的指标中台的分享，也有介绍到自动化建模的方案。不过应该比较简单，采用同名用意字段组合

**Comment by jerryjzhang** [comment]
Duplicate issue
