### ISSUE TITLE
构建知识库问答能力，默认增加SuperSonic文档问答处理

### ISSUE THREAD

**Issue by lexluo09** [tencentmusic/supersonic#949]
1、构建SuperSonic知识库，支持pdf、md文档信息录入；
2、SuperSonic启动后，默认问答助理，可以基于文档回答进行问答；

**Comment by dawsongzhao0523** [comment]
补充：建议优先支持，问答输入框，直接上传excel/csv文件（将文件存储到duckdb）做数据问答或分析，类似gpt-4o数据分析示例：https://www.bilibili.com/video/BV1yT421D7XN/

**Comment by jerryjzhang** [comment]
> 补充：建议优先支持，问答输入框，直接上传excel/csv文件（将文件存储到duckdb）做数据问答或分析，类似gpt-4o数据分析示例：https://www.bilibili.com/video/BV1yT421D7XN/

从描述上看，跟该issue是不同的功能点。这里想支持的是，对SuperSonic自身文档提供问答能力，方便新用户了解如何使用SuperSonic。 @dawsongzhao0523 建议的功能，可以增加到排期中，不过暂时不属于SuperSonic最核心定位的能力。
