### ISSUE TITLE
使用postgresql数据源时,日期函数替换错误

### ISSUE THREAD

**Issue by hzhili** [tencentmusic/supersonic#950]
![image](https://github.com/tencentmusic/supersonic/assets/39455920/3d85a7a6-28d4-4157-a047-7dbce8f0ee1d)
目前PostgresqlAdaptor替换为这三个函数,但是postgresql数据库中不支持这三个函数,是否能修改为to_char或者extract函数

**Comment by lexluo09** [comment]
感谢您的反馈，我们看看
