### ISSUE TITLE
Fail to build on MacOS with Apple Silicon chips due to unsupported platform by `cross-env` nodejs package

### ISSUE THREAD

**Issue by bowenliang123** [tencentmusic/supersonic#97]
Version: 0.7.5-SNAPSHOT
Branch: master
Machine: Macbook Pro 14' 2021 (Apple M1 Pro)

Failed to build source code on MacOS with M1 chips.

Steps:
1. download source code on master branch
2. run `sh assembly/bin/supersonic-build.sh`, as instructed by wiki 
3. Failed to finish the build

```
x launchers-standalone-0.7.5-SNAPSHOT/llmparser/sql/prompt_maker.py
x launchers-standalone-0.7.5-SNAPSHOT/llmparser/sql/output_parser.py
x launchers-standalone-0.7.5-SNAPSHOT/llmparser/sql/examples_reload_run.py
cp: /Users/bw/dev/supersonic/assembly/build/webapp/*: No such file or directory
assembly/bin/supersonic-build.sh: line 48: ../../launchers/chat/target/classes/webapp/supersonic.config.json: No such file or directory
assembly/bin/supersonic-build.sh: line 48: ../../launchers/semantic/target/classes/webapp/supersonic.config.json: No such file or directory
```

Related failures when installing npm packages:

```
../../node_modules/.pnpm/esbuild@0.7.22/node_modules/esbuild: Running postinstall script, failed in 62ms
.../esbuild@0.7.22/node_modules/esbuild postinstall$ node install.js
│ Unsupported platform: darwin arm64 LE
└─ Failed in 62ms at /Users/bw/dev/supersonic/webapp/node_modules/.pnpm/esbuild@0.7.22/node_modules/esbuild
../../node_modules/.pnpm/esbuild@0.12.15/node_modules/esbuild: Running postinstall script...
 ELIFECYCLE  Command failed with exit code 1.

> supersonic-chat-sdk@0.0.0 build /Users/bw/dev/supersonic/webapp/packages/chat-sdk
> npm run clean && npm run build-es
```

The `corss-env` package has been deprecated since Jan 2021. https://github.com/kentcdodds/cross-env/issues/257 
 It seems it does not support M1 chips.

**Comment by williamhuanliu** [comment]
After upgrading the cross-env version to 0.7.3, this issue has been resolved. Thank you for your feedback. https://github.com/tencentmusic/supersonic/pull/104

**Comment by bowenliang123** [comment]
Thanks for the help and improvements. @williamhliu

**Comment by motdotla** [comment]
cross-env has been in maintenance mode for 4 years with no new features. you guys might find [`dotenvx`](https://github.com/dotenvx/dotenvx) a useful and more up to date alternative.
