### ISSUE TITLE
语义建模创建度量/指标时，支持聚合函数默认为空

### ISSUE THREAD

**Issue by lxwcodemonkey** [tencentmusic/supersonic#976]
**背景**
存在类似粉丝数，份额这样的指标，已经是经过计算好的，且无法再通过聚合算子进行计算，因此在创建的时候可以指定聚合方法为空

**改动点**
1. 建模创建度量时，现在强制需要指定聚合算子，后续可以不再指定聚合算子
2. 创建字段创建指标时，不强制需要表达式中包含聚合算子
3. 查询时，对于没有配置聚合函数的指标/度量，按明细模式进行查询，不加聚合方法

**Comment by jipeli** [comment]
默认聚合函数的获取  (#984)
1. 按照度量创建，取第一个度量的聚合函数
2. 按照字段创建，取表达式的聚合函数
3. 按照指标创建，递归取第一个指标的聚合函数
