### ISSUE TITLE
在【问答页面】中，【智能助理】过多时，无法显示最新的智能助理，需通过缩放页面进行选择

### ISSUE THREAD

**Issue by mxli441** [tencentmusic/supersonic#981]
在【问答页面】中，【智能助理】过多时，无法显示最新的智能助理，需通过缩放页面进行选择，是否可以配置第一页，第二页类似的页面
![1715409866328](https://github.com/tencentmusic/supersonic/assets/70192192/0c149692-f270-490f-b0dc-4dab1a21585d)
缩小页面后才能看到
![1715409936006](https://github.com/tencentmusic/supersonic/assets/70192192/9375bdb2-a40a-4c43-8dfb-0703120858eb)

**Comment by jerryjzhang** [comment]
需求收到，会安排开发

**Comment by williamhuanliu** [comment]
这个问题已修复https://github.com/tencentmusic/supersonic/pull/1004
