### ISSUE TITLE
【语义建模】引入“模型集”概念，简化“主题域”层级的管理

### ISSUE THREAD

**Issue by jerryjzhang** [tencentmusic/supersonic#996]
### 需求说明

当前主题域层面包含【模型管理】、【画布】【数据集管理】、【标签对象管理】、【术语管理】、【权限管理】六大管理模块，管理粒度显得比较臃肿，引入“模型集”来简化：
- 在“主题域”下创建“模型集”，新建一个主题域，默认也会创建一个模型集（名称“默认模型集”）
- “主题域”下管理模块有：【数据集管理】、【标签对象管理】、【术语管理】、【权限管理】
- ”模型集“下管理模块有：【模型管理】【画布】
- 进一步，考虑不显式体现【模型管理】和【画布】，做一个交互开关来切换”列表“和”画布“两种模式

**Comment by sevenliu1896** [comment]
#1009 已完成
